// runtime/codegen/emosqp/solver_meta.zig — Generated by scripts/gen_emosqp_test.py — DO NOT EDIT.
// The baked solver's variable count. runtime/lower.zig comptime-checks that
// any graph containing a .solve_qp node matches this n_vars at build time.

pub const n_vars: usize = 30;
