// runtime/codegen/emosqp/solver_meta.zig — Generated by scripts/gen_emosqp_test.py — DO NOT EDIT.
// The baked solver's variable count. runtime/lower.zig comptime-checks that
// any graph containing a .solve_qp node matches this n_vars at build time.
// The remaining consts are provenance surfaced in the build manifest.

pub const n_vars: usize = 30;
pub const n_cons: usize = 60;
pub const eps: f64 = 1e-06;
pub const config = "configs/controllers/mpc_lti_base.toml";
