/*
 * This file was autogenerated by OSQP on Mon Sep  7 12:40:40 2026
 * 
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#ifndef WORKSPACE_H
#define WORKSPACE_H

#include "osqp_api_types.h"

#ifdef __cplusplus
extern "C" {
#endif

  extern OSQPSolver solver;

#ifdef __cplusplus
}
#endif

#endif /* ifndef WORKSPACE_H */
