// Generated by shinro.codegen.lower_zig — DO NOT EDIT.
// A ComposedGraph serialized as a comptime data table.

pub const Op = enum {
    cst, inp, out, matmul, add, sub, mul, div, neg,
    transpose, inv, reshape, clip, where_op, any,
    copy, tanh, relu, exp, argmax, one_hot, slice,
    sin, cos, stack, solve_qp,
};

pub const Node = struct {
    op: Op,
    inputs: []const usize,
    rows: usize,
    cols: usize,
    aux: usize,
};

pub const buf_len = 318;
pub const n_outputs = 1;

pub const offsets = [_]usize{
    0, 3, 6, 9, 12, 21, 24, 27, 36, 39, 48, 51, 54, 63, 72, 81, 90, 99, 108, 117, 126, 135, 144, 153, 162, 171, 180, 189, 198, 207, 210, 219, 222, 225, 228, 231, 234, 243, 252, 261, 270, 279, 282, 285, 294, 297, 300, 303, 306, 315,
};

pub const nodes = [_]Node{
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 3 },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 6 },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 9 },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 12 },
    .{ .op = .reshape, .inputs = &.{0}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .reshape, .inputs = &.{2}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .matmul, .inputs = &.{7, 3}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 9 },
    .{ .op = .matmul, .inputs = &.{9, 6}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .add, .inputs = &.{8, 10}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 18 },
    .{ .op = .matmul, .inputs = &.{12, 4}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 27 },
    .{ .op = .matmul, .inputs = &.{13, 14}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 36 },
    .{ .op = .add, .inputs = &.{15, 16}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 45 },
    .{ .op = .matmul, .inputs = &.{18, 17}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 54 },
    .{ .op = .matmul, .inputs = &.{19, 20}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 63 },
    .{ .op = .add, .inputs = &.{21, 22}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 72 },
    .{ .op = .matmul, .inputs = &.{17, 24}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .inv, .inputs = &.{23}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .matmul, .inputs = &.{25, 26}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 81 },
    .{ .op = .matmul, .inputs = &.{28, 11}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 90 },
    .{ .op = .matmul, .inputs = &.{30, 6}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .add, .inputs = &.{29, 31}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .sub, .inputs = &.{5, 32}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .matmul, .inputs = &.{27, 33}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .add, .inputs = &.{11, 34}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 99 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 108 },
    .{ .op = .matmul, .inputs = &.{27, 37}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .sub, .inputs = &.{36, 38}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .matmul, .inputs = &.{39, 17}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .reshape, .inputs = &.{35}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .sub, .inputs = &.{1, 41}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 117 },
    .{ .op = .matmul, .inputs = &.{43, 42}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .clip, .inputs = &.{44}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .out, .inputs = &.{45}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .out, .inputs = &.{35}, .rows = 3, .cols = 1, .aux = 1 },
    .{ .op = .out, .inputs = &.{40}, .rows = 3, .cols = 3, .aux = 2 },
    .{ .op = .out, .inputs = &.{45}, .rows = 3, .cols = 1, .aux = 3 },
};

pub const const_blob = [_]f64{
    0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.47ae147ae147bp-6, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-6, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-6, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.47ae147ae147bp-7, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-7, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-7, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.999999999999ap-4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.999999999999ap-4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.999999999999ap-4, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.72a8f38fccafdp+4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.72a8f38fccafdp+4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.1e9b2675a6625p+4,
};

pub const clip_lo = [_]f64{-0x1.0000000000000p-1, -0x1.0000000000000p-1, -0x1.0000000000000p+0};
pub const clip_hi = [_]f64{0x1.0000000000000p-1, 0x1.0000000000000p-1, 0x1.0000000000000p+0};

pub const output_offsets = [_]usize{0};
pub const state_offsets = [_]usize{0, 3, 12};

