// Generated by shinro.codegen.lower_zig — DO NOT EDIT.
// A ComposedGraph serialized as a comptime data table.

pub const Op = enum {
    cst, inp, out, matmul, add, sub, mul, div, neg,
    transpose, inv, reshape, clip, where_op, any,
};

pub const Node = struct {
    op: Op,
    inputs: []const usize,
    rows: usize,
    cols: usize,
    aux: usize,
};

pub const buf_len = 201;
pub const n_outputs = 1;

pub const offsets = [_]usize{
    0, 3, 6, 9, 12, 15, 18, 27, 30, 39, 42, 45, 54, 63, 72, 81, 90, 93, 102, 105, 108, 111, 114, 117, 126, 135, 144, 153, 162, 171, 174, 177, 186, 189, 192, 195, 198,
};

pub const nodes = [_]Node{
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 3 },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 6 },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 9 },
    .{ .op = .reshape, .inputs = &.{0}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .reshape, .inputs = &.{2}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .matmul, .inputs = &.{6, 3}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 9 },
    .{ .op = .matmul, .inputs = &.{8, 5}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .add, .inputs = &.{7, 9}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 18 },
    .{ .op = .inv, .inputs = &.{11}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 27 },
    .{ .op = .matmul, .inputs = &.{13, 12}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 36 },
    .{ .op = .matmul, .inputs = &.{15, 10}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 45 },
    .{ .op = .matmul, .inputs = &.{17, 5}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .add, .inputs = &.{16, 18}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .sub, .inputs = &.{4, 19}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .matmul, .inputs = &.{14, 20}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .add, .inputs = &.{10, 21}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 54 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 63 },
    .{ .op = .matmul, .inputs = &.{14, 24}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .sub, .inputs = &.{23, 25}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 72 },
    .{ .op = .matmul, .inputs = &.{26, 27}, .rows = 3, .cols = 3, .aux = 0 },
    .{ .op = .reshape, .inputs = &.{22}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .sub, .inputs = &.{1, 29}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 81 },
    .{ .op = .matmul, .inputs = &.{31, 30}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .clip, .inputs = &.{32}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .out, .inputs = &.{33}, .rows = 3, .cols = 1, .aux = 0 },
    .{ .op = .out, .inputs = &.{22}, .rows = 3, .cols = 1, .aux = 1 },
    .{ .op = .out, .inputs = &.{33}, .rows = 3, .cols = 1, .aux = 2 },
};

pub const const_blob = [_]f64{
    0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.47ae147ae147bp-6, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-6, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-6, 0x1.ae147ae147ae2p-3, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.ae147ae147ae2p-3, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.ae147ae147ae2p-3, 0x1.c28f5c28f5c29p-4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.c28f5c28f5c29p-4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.c28f5c28f5c29p-4, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.c28f5c28f5c29p-4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.c28f5c28f5c29p-4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.c28f5c28f5c29p-4, 0x1.72a8f38fccafdp+4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.72a8f38fccafdp+4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.1e9b2675a6625p+4,
};

pub const clip_lo = [_]f64{-0x1.0000000000000p-1, -0x1.0000000000000p-1, -0x1.0000000000000p+0};
pub const clip_hi = [_]f64{0x1.0000000000000p-1, 0x1.0000000000000p-1, 0x1.0000000000000p+0};

pub const output_offsets = [_]usize{0};
pub const state_offsets = [_]usize{0, 3};

