// runtime/lower.zig — comptime graph VM: walks the generated node table and
// specializes one step of the closed loop at compile time.
//
// This is the Zig mirror of interpreter.py's dispatch loop. The graph data
// (op enum, inputs, shapes) is generated by shinro.codegen.lower_zig into
// graph_data.zig; the *code* here is handwritten once and never regenerated.
//
// The VM is comptime-specialized: `inline for` over the node table unrolls the
// loop, so every node's shapes are comptime constants and every array is a
// fixed-size stack slice of one contiguous buffer. Nothing is allocated, no
// dispatch happens at runtime — the "fixed at compile time" guarantee.
//
// C ABI (all flat, row-major f64 buffers; layout known to the host from the
// ComposedGraph port lists):
//   shinro_step(inputs, outputs, state_out)
//   - inputs:    host inputs packed in cg.inputs order (e.g. y, x_ref, u_prev
//                followed by the estimator's state_* recurrent ports)
//   - outputs:   packed in cg.outputs order
//   - state_out: packed in cg.state_outputs order (recurrent → next tick)

const std = @import("std");
// The generated graph and the bake's n_vars are anonymous imports wired by
// build.zig from -Dgraph / -Dsolver_dir (defaults: runtime/graph_data.zig and
// runtime/codegen/emosqp/solver_meta.zig).
const g = @import("graph_data");
const sm = @import("solver_meta");
const la = @import("linalg.zig");
const qp = @import("qp.zig");

/// Run one tick of the closed-loop step through the generated node table.
///
/// The C-ABI entry point (exported as `shinro_step`) that the host calls once
/// per control tick. All buffers are flat, row-major f64; their layout is
/// known to the host from the ComposedGraph port lists:
///
/// - `inputs`: host inputs packed in `cg.inputs` order (e.g. `y`, `x_ref`,
///   `u_prev` followed by the estimator's `state_*` recurrent ports)
/// - `outputs`: packed in `cg.outputs` order
/// - `state_out`: packed in `cg.state_outputs` order (recurrent → next tick)
///
/// The `inline for` over `g.nodes` unrolls the whole node table at compile
/// time, so every node's shape is a comptime constant and every array is a
/// fixed-size slice of the single stack buffer — no heap, no runtime dispatch.
///
/// Args:
///     inputs: Flat buffer of this tick's host inputs.
///     outputs: Flat buffer where this tick's output ports are written.
///     state_out: Flat buffer where this tick's recurrent state outputs are
///         written (fed back as state inputs next tick).
export fn shinro_step(inputs: [*]const f64, outputs: [*]f64, state_out: [*]f64) void {
    var buf: [g.buf_len]f64 align(16) = undefined;

    inline for (g.nodes, 0..) |node, i| {
        const out = buf[g.offsets[i]..][0 .. node.rows * node.cols];

        switch (node.op) {
            .cst => {
                inline for (0..node.rows * node.cols) |j| out[j] = g.const_blob[node.aux + j];
            },
            .inp => {
                inline for (0..node.rows * node.cols) |j| out[j] = inputs[node.aux + j];
            },
            .out => {
                const src = node_input(g.nodes[0..], node, &buf);
                if (node.aux < g.n_outputs) {
                    inline for (0..node.rows * node.cols) |j| outputs[g.output_offsets[node.aux] + j] = src[j];
                } else {
                    inline for (0..node.rows * node.cols) |j| state_out[g.state_offsets[node.aux - g.n_outputs] + j] = src[j];
                }
            },
            .matmul => {
                const a = node_input(g.nodes[0..], node, &buf);
                const b = node_input_at(g.nodes[0..], node.inputs[1], &buf);
                if (node.cols == 1 and g.nodes[node.inputs[0]].cols == 1) {
                    // vecmat: (k,) @ (k, n) -> (n,)
                    const r = la.vecmat(g.nodes[node.inputs[0]].rows, node.rows, a, b);
                    inline for (0..node.rows * node.cols) |j| out[j] = r[j];
                } else if (node.cols == 1) {
                    // matvec: (m, k) @ (k,) -> (m,)
                    const r = la.matvec(node.rows, g.nodes[node.inputs[1]].rows, a, b);
                    inline for (0..node.rows * node.cols) |j| out[j] = r[j];
                } else {
                    // matmul: (m, k) @ (k, n) -> (m, n)
                    const r = la.matmul(node.rows, g.nodes[node.inputs[0]].cols, node.cols, a, b);
                    inline for (0..node.rows * node.cols) |j| out[j] = r[j];
                }
            },
            .add => ew2(g.nodes[0..], node, i, &buf, .add),
            .sub => ew2(g.nodes[0..], node, i, &buf, .sub),
            .mul => ew2(g.nodes[0..], node, i, &buf, .mul),
            .div => ew2(g.nodes[0..], node, i, &buf, .div),
            .ne => ew2(g.nodes[0..], node, i, &buf, .ne),
            .neg => {
                const s = node_input(g.nodes[0..], node, &buf);
                inline for (0..node.rows * node.cols) |j| out[j] = -s[j];
            },
            .transpose => {
                const s = node_input(g.nodes[0..], node, &buf);
                const r = g.nodes[node.inputs[0]].rows;
                const c = g.nodes[node.inputs[0]].cols;
                inline for (0..c) |row| {
                    inline for (0..r) |col| out[col * c + row] = s[row * r + col];
                }
            },
            .inv => {
                const s = node_input(g.nodes[0..], node, &buf);
                const r = la.inv(node.rows, s);
                inline for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .reshape => {
                const s = node_input(g.nodes[0..], node, &buf);
                inline for (0..node.rows * node.cols) |j| out[j] = s[j];
            },
            .clip => {
                const s = node_input(g.nodes[0..], node, &buf);
                inline for (0..node.rows * node.cols) |j| {
                    out[j] = std.math.clamp(s[j], g.clip_lo[node.aux + j], g.clip_hi[node.aux + j]);
                }
            },
            .where_op => {
                const cond = node_input(g.nodes[0..], node, &buf);
                const a = node_input_at(g.nodes[0..], node.inputs[1], &buf);
                const b = node_input_at(g.nodes[0..], node.inputs[2], &buf);
                inline for (0..node.rows * node.cols) |j| out[j] = if (cond[j] != 0.0) a[j] else b[j];
            },
            .any => {
                const s = node_input(g.nodes[0..], node, &buf);
                var found = false;
                inline for (0..g.nodes[node.inputs[0]].rows * g.nodes[node.inputs[0]].cols) |j| {
                    if (s[j] != 0.0) found = true;
                }
                out[0] = if (found) 1.0 else 0.0;
            },
            // deterministic-policy ops (issue #13): elementwise maps, a
            // reduction (argmax), an expansion (one_hot), and shape glue
            // (copy / slice). None allocate — all iterate comptime-known
            // flat buffers. tanh/relu/exp preserve shape; argmax collapses
            // to a scalar (stored as f64 in the buffer); one_hot expands a
            // scalar index to a depth-row; copy/slice are flat copies with
            // slice's `aux` holding the input offset.
            .copy => {
                const s = node_input(g.nodes[0..], node, &buf);
                inline for (0..node.rows * node.cols) |j| out[j] = s[j];
            },
            .tanh => {
                const s = node_input(g.nodes[0..], node, &buf);
                const r = la.tanh(node.rows * node.cols, s);
                inline for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .relu => {
                const s = node_input(g.nodes[0..], node, &buf);
                const r = la.relu(node.rows * node.cols, s);
                inline for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .exp => {
                const s = node_input(g.nodes[0..], node, &buf);
                const r = la.elementwise_exponential(node.rows * node.cols, s);
                inline for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .sin => {
                const s = node_input(g.nodes[0..], node, &buf);
                const r = la.sin_vec(node.rows * node.cols, s);
                inline for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .cos => {
                const s = node_input(g.nodes[0..], node, &buf);
                const r = la.cos_vec(node.rows * node.cols, s);
                inline for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .argmax => {
                const s = node_input(g.nodes[0..], node, &buf);
                const n_in = g.nodes[node.inputs[0]].rows * g.nodes[node.inputs[0]].cols;
                const idx = la.argmax(n_in, s);
                out[0] = @floatFromInt(idx);
            },
            .one_hot => {
                const s = node_input(g.nodes[0..], node, &buf);
                const idx: usize = @intFromFloat(s[0]);
                const r = la.onehot(node.rows, idx);
                inline for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .slice => {
                const s = node_input(g.nodes[0..], node, &buf);
                inline for (0..node.rows * node.cols) |j| out[j] = s[node.aux + j];
            },
            // stack([a, b, ...]) along a new leading axis (numpy axis=0). Each
            // input contributes its flat length to consecutive output rows; all
            // inputs share the same shape (enforced at trace time), so the
            // output flat length is n_inputs * in_len == node.rows * node.cols.
            .stack => {
                inline for (node.inputs, 0..) |inp_idx, row| {
                    const src = node_input_at(g.nodes[0..], inp_idx, &buf);
                    const in_len = g.nodes[inp_idx].rows * g.nodes[inp_idx].cols;
                    inline for (0..in_len) |j| out[row * in_len + j] = src[j];
                }
            },
            // .solve_qp — the convergence-iterative MPC op. The problem data
            // (P, A, l, u) and the pre-factorized KKT matrix are baked into the
            // statically-allocated `solver` global by the codegen C
            // (runtime/codegen/emosqp/). Only the linear cost q changes per
            // tick: it is read from the node's input slot and written in via
            // osqp_update_data_vec, then the full solution lands in this
            // node's output slot (u[:m] is sliced out by a downstream op).
            // The node's output size must match the baked problem's n_vars —
            // enforced here at compile time, so a graph lowered against the
            // wrong bake refuses to build instead of silently linking a
            // shape-mismatched solver.
            .solve_qp => {
                comptime {
                    if (node.rows * node.cols != sm.n_vars) {
                        @compileError("graph solve_qp node output size (" ++
                            std.fmt.comptimePrint("{d}", .{node.rows * node.cols}) ++
                            ") does not match baked solver n_vars (" ++
                            std.fmt.comptimePrint("{d}", .{sm.n_vars}) ++
                            ") — rebuild with the matching -Dsolver_dir");
                    }
                }
                const q_vec = node_input(g.nodes[0..], node, &buf);
                qp.solve_qp(q_vec, out);
            },
        }
    }
}

// --- helpers ---------------------------------------------------------------

const BinOp = enum { add, sub, mul, div, ne };

/// Elementwise binary op with broadcast: each operand is either the same
/// length as the output, or a single element (0-d / size-1 broadcast).
/// inline so the comptime-known node bounds reach the inline-for.
/// Elementwise binary op with broadcast.
///
/// Each operand is either the same length as the output or a single element
/// (0-d / size-1 broadcast), mirroring numpy's broadcasting for the shapes
/// the tracer allows. `inline` so the comptime-known node bounds reach the
/// `inline for`.
///
/// Args:
///     nodes: The full generated node table (for shape lookup).
///     node: The current add/sub/mul/div/ne node.
///     self_idx: The node's index in `nodes` (its buffer offset).
///     buf: The shared step buffer (written at the node's offset).
///     op: Which binary op to apply (add, sub, mul, div).
inline fn ew2(nodes: []const g.Node, node: g.Node, self_idx: usize, buf: *[g.buf_len]f64, op: BinOp) void {
    const a = node_input_at(nodes, node.inputs[0], buf);
    const b = node_input_at(nodes, node.inputs[1], buf);
    const na = nodes[node.inputs[0]].rows * nodes[node.inputs[0]].cols;
    const nb = nodes[node.inputs[1]].rows * nodes[node.inputs[1]].cols;
    var out = buf.*[g.offsets[self_idx] ..][0 .. node.rows * node.cols];
    inline for (0..node.rows * node.cols) |j| {
        const av = if (na == 1) a[0] else a[j];
        const bv = if (nb == 1) b[0] else b[j];
        out[j] = switch (op) {
            .add => av + bv,
            .sub => av - bv,
            .mul => av * bv,
            .div => av / bv,
            // Inequality as a 1.0/0.0 flag — the graph's boolean repr,
            // consumed by where_op downstream (e.g. PID anti-windup).
            .ne => if (av != bv) 1.0 else 0.0,
        };
    }
}

/// Read a node's first input from the shared buffer.
///
/// Args:
///     nodes: The full generated node table (for shape lookup).
///     node: The consumer node whose first input to read.
///     buf: The shared step buffer.
///
/// Returns:
///     A fixed-length slice of `buf` covering the input node's slot.
fn node_input(nodes: []const g.Node, node: g.Node, buf: *[g.buf_len]f64) []const f64 {
    return node_input_at(nodes, node.inputs[0], buf);
}

/// Read an arbitrary node's output slot from the buffer by node index.
///
/// Args:
///     nodes: The full generated node table (for shape lookup).
///     idx: The node index whose output to read.
///     buf: The shared step buffer.
///
/// Returns:
///     A fixed-length slice of `buf` covering node `idx`'s `rows*cols` f64s.
fn node_input_at(nodes: []const g.Node, idx: usize, buf: *[g.buf_len]f64) []const f64 {
    return buf.*[g.offsets[idx]..][0 .. nodes[idx].rows * nodes[idx].cols];
}
