// runtime/lower.zig — comptime graph VM: walks the generated node table and
// specializes one step of the closed loop at compile time.
//
// This is the Zig mirror of interpreter.py's dispatch loop. The graph data
// (op enum, inputs, shapes) is generated by shinro.codegen.lower_zig into
// graph_data.zig; the *code* here is handwritten once and never regenerated.
//
// The VM is comptime-specialized: `inline for` over the node table unrolls the
// loop, so every node's shapes are comptime constants and every array is a
// fixed-size stack slice of one contiguous buffer. Nothing is allocated, no
// dispatch happens at runtime — the "fixed at compile time" guarantee.
//
// C ABI (all flat, row-major f64 buffers; layout known to the host from the
// ComposedGraph port lists):
//   shinro_step(inputs, outputs, state_out)
//   - inputs:    y, x_ref, u_prev, state_x_hat packed in cg.inputs order
//   - outputs:   packed in cg.outputs order
//   - state_out: packed in cg.state_outputs order (recurrent → next tick)

const std = @import("std");
const g = @import("graph_data.zig");
const la = @import("linalg.zig");

export fn shinro_step(inputs: [*]const f64, outputs: [*]f64, state_out: [*]f64) void {
    var buf: [g.buf_len]f64 align(16) = undefined;

    inline for (g.nodes, 0..) |node, i| {
        const out = buf[g.offsets[i]..][0 .. node.rows * node.cols];

        switch (node.op) {
            .cst => {
                inline for (0..node.rows * node.cols) |j| out[j] = g.const_blob[node.aux + j];
            },
            .inp => {
                inline for (0..node.rows * node.cols) |j| out[j] = inputs[node.aux + j];
            },
            .out => {
                const src = node_input(g.nodes[0..], node, &buf);
                if (node.aux < g.n_outputs) {
                    inline for (0..node.rows * node.cols) |j| outputs[g.output_offsets[node.aux] + j] = src[j];
                } else {
                    inline for (0..node.rows * node.cols) |j| state_out[g.state_offsets[node.aux - g.n_outputs] + j] = src[j];
                }
            },
            .matmul => {
                const a = node_input(g.nodes[0..], node, &buf);
                const b = node_input_at(g.nodes[0..], node.inputs[1], &buf);
                if (node.cols == 1 and g.nodes[node.inputs[0]].cols == 1) {
                    // vecmat: (k,) @ (k, n) -> (n,)
                    const r = la.vecmat(g.nodes[node.inputs[0]].rows, node.rows, a, b);
                    inline for (0..node.rows * node.cols) |j| out[j] = r[j];
                } else if (node.cols == 1) {
                    // matvec: (m, k) @ (k,) -> (m,)
                    const r = la.matvec(node.rows, g.nodes[node.inputs[1]].rows, a, b);
                    inline for (0..node.rows * node.cols) |j| out[j] = r[j];
                } else {
                    // matmul: (m, k) @ (k, n) -> (m, n)
                    const r = la.matmul(node.rows, g.nodes[node.inputs[0]].cols, node.cols, a, b);
                    inline for (0..node.rows * node.cols) |j| out[j] = r[j];
                }
            },
            .add => ew2(g.nodes[0..], node, i, &buf, .add),
            .sub => ew2(g.nodes[0..], node, i, &buf, .sub),
            .mul => ew2(g.nodes[0..], node, i, &buf, .mul),
            .div => ew2(g.nodes[0..], node, i, &buf, .div),
            .neg => {
                const s = node_input(g.nodes[0..], node, &buf);
                inline for (0..node.rows * node.cols) |j| out[j] = -s[j];
            },
            .transpose => {
                const s = node_input(g.nodes[0..], node, &buf);
                const r = g.nodes[node.inputs[0]].rows;
                const c = g.nodes[node.inputs[0]].cols;
                inline for (0..c) |row| {
                    inline for (0..r) |col| out[col * c + row] = s[row * r + col];
                }
            },
            .inv => {
                const s = node_input(g.nodes[0..], node, &buf);
                const r = la.inv(node.rows, s);
                inline for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .reshape => {
                const s = node_input(g.nodes[0..], node, &buf);
                inline for (0..node.rows * node.cols) |j| out[j] = s[j];
            },
            .clip => {
                const s = node_input(g.nodes[0..], node, &buf);
                inline for (0..node.rows * node.cols) |j| {
                    out[j] = std.math.clamp(s[j], g.clip_lo[node.aux + j], g.clip_hi[node.aux + j]);
                }
            },
            .where_op => {
                const cond = node_input(g.nodes[0..], node, &buf);
                const a = node_input_at(g.nodes[0..], node.inputs[1], &buf);
                const b = node_input_at(g.nodes[0..], node.inputs[2], &buf);
                inline for (0..node.rows * node.cols) |j| out[j] = if (cond[j] != 0.0) a[j] else b[j];
            },
            .any => {
                const s = node_input(g.nodes[0..], node, &buf);
                var found = false;
                inline for (0..g.nodes[node.inputs[0]].rows * g.nodes[node.inputs[0]].cols) |j| {
                    if (s[j] != 0.0) found = true;
                }
                out[0] = if (found) 1.0 else 0.0;
            },
        }
    }
}

// --- helpers ---------------------------------------------------------------

const BinOp = enum { add, sub, mul, div };

/// Elementwise binary op with broadcast: each operand is either the same
/// length as the output, or a single element (0-d / size-1 broadcast).
/// inline so the comptime-known node bounds reach the inline-for.
inline fn ew2(nodes: []const g.Node, node: g.Node, self_idx: usize, buf: *[g.buf_len]f64, op: BinOp) void {
    const a = node_input_at(nodes, node.inputs[0], buf);
    const b = node_input_at(nodes, node.inputs[1], buf);
    const na = nodes[node.inputs[0]].rows * nodes[node.inputs[0]].cols;
    const nb = nodes[node.inputs[1]].rows * nodes[node.inputs[1]].cols;
    var out = buf.*[g.offsets[self_idx] ..][0 .. node.rows * node.cols];
    inline for (0..node.rows * node.cols) |j| {
        const av = if (na == 1) a[0] else a[j];
        const bv = if (nb == 1) b[0] else b[j];
        out[j] = switch (op) {
            .add => av + bv,
            .sub => av - bv,
            .mul => av * bv,
            .div => av / bv,
        };
    }
}

fn node_input(nodes: []const g.Node, node: g.Node, buf: *[g.buf_len]f64) []const f64 {
    return node_input_at(nodes, node.inputs[0], buf);
}

fn node_input_at(nodes: []const g.Node, idx: usize, buf: *[g.buf_len]f64) []const f64 {
    return buf.*[g.offsets[idx]..][0 .. nodes[idx].rows * nodes[idx].cols];
}
