// runtime/tests/emosqp.zig — the OSQP codegen static solver driven from Zig.
//
// The generated code (runtime/codegen/emosqp/) bakes the base MPC problem into
// a statically-allocated OSQPSolver global — no malloc, no libosqp dependency.
// This test updates the linear cost q (the only per-tick input for MPC) and
// compares the solution against the Python oracle.
//
// The test vectors live in emosqp_data.zig (generated by
// scripts/gen_emosqp_test.py). This file is handwritten and never regenerated,
// following the lowerer's "Python emits data only, never code" doctrine.

const std = @import("std");
const data = @import("emosqp_data.zig");
const c = @cImport({ @cInclude("osqp.h"); });

// The statically-allocated solver from workspace.c.
extern var solver: c.OSQPSolver;

test "codegen static solver matches python oracle" {
    // Update the linear cost (the only per-tick input for MPC), then solve.
    const rc = c.osqp_update_data_vec(&solver, &data.q, null, null);
    try std.testing.expectEqual(@as(c.OSQPInt, 0), rc);

    _ = c.osqp_solve(&solver);
    const status = solver.info.*.status_val;
    try std.testing.expectEqual(@as(c.OSQPInt, 1), status); // OSQP_SOLVED

    const x = solver.solution.*.x;
    for (0..data.q.len) |j| {
        try std.testing.expectApproxEqAbs(data.u_expected[j], x[j], 1e-3);
    }
}