// runtime/tests/emosqp_data.zig — Generated by scripts/gen_emosqp_test.py — DO NOT EDIT.
// Test vectors consumed by the handwritten oracle test runtime/tests/emosqp.zig.
//
// q = Fᵀ x₀ for the sample state x₀ = [0.1, -0.05000000000000002, -0.2];
// u_expected is the Python oracle's solution (same OSQP algorithm, eps=1e-06).
// Floats are hex literals — bit-exact round-trip of the f64 the oracle produced.

pub const q = [_]f64{
    0x1.0000000000000p+2, -0x1.0000000000002p+1, -0x1.0000000000000p+2, 0x1.ccccccccccccdp+1, -0x1.cccccccccccd0p+0, -0x1.ccccccccccccdp+1, 0x1.999999999999ap+1, -0x1.999999999999cp+0, -0x1.999999999999ap+1, 0x1.6666666666667p+1, -0x1.6666666666668p+0, -0x1.6666666666667p+1, 0x1.3333333333334p+1, -0x1.3333333333335p+0, -0x1.3333333333334p+1, 0x1.0000000000000p+1, -0x1.0000000000002p+0, -0x1.0000000000000p+1, 0x1.999999999999ap+0, -0x1.999999999999cp-1, -0x1.999999999999ap+0, 0x1.3333333333334p+0, -0x1.3333333333335p-1, -0x1.3333333333334p+0, 0x1.999999999999ap-1, -0x1.999999999999cp-2, -0x1.999999999999ap-1, 0x1.999999999999ap-2, -0x1.999999999999cp-3, -0x1.999999999999ap-2,
};

pub const u_expected = [_]f64{
    -0x1.ffffffff69178p-2, 0x1.ffffffffdb555p-2, 0x1.ffffffffc48a1p-1, -0x1.ffffffff9274cp-2, 0x1.fffffffff0596p-2, 0x1.ffffffffdc9fbp-1, -0x1.ffffffffadb17p-2, 0x1.ffffffffff4e7p-2, 0x1.ffffffffee259p-1, -0x1.ffffffffc3731p-2, 0x1.da532c302699ap-2, 0x1.fffffffffc956p-1, -0x1.ffffffffd93dbp-2, 0x1.fce8e22122138p-3, 0x1.0000000005645p+0, -0x1.ffffffffd44aap-2, 0x1.10bbc65444a48p-3, 0x1.fffffffffebadp-1, -0x1.ffffffffe9c9fp-2, 0x1.234d26ed552a5p-4, 0x1.0000000002708p+0, -0x1.0000000009917p-1, 0x1.335007eec5d2bp-5, 0x1.e9e3154283e81p-1, -0x1.a08ad8f33c2b9p-2, 0x1.35e523f73c7c4p-6, 0x1.18aa1984afa0ep-1, -0x1.5b1e5f7aef1dep-3, 0x1.023ef34ded6b8p-7, 0x1.fe4c8b7bc1d96p-3,
};
