// runtime/tests/emosqp_data.zig — Generated by scripts/gen_emosqp_test.py — DO NOT EDIT.
// Test vectors consumed by the handwritten oracle test runtime/tests/emosqp.zig.
//
// q = Fᵀ x₀ for the sample state x₀ = [0.1, -0.2, 0.3];
// u_expected is the Python oracle's solution (same OSQP algorithm, eps=1e-06).
// Floats are hex literals — bit-exact round-trip of the f64 the oracle produced.

pub const q = [_]f64{
    0x1.0000000000000p+2, -0x1.0000000000000p+3, 0x1.8000000000000p+2, 0x1.ccccccccccccdp+1, -0x1.ccccccccccccdp+2, 0x1.5999999999999p+2, 0x1.999999999999ap+1, -0x1.999999999999ap+2, 0x1.3333333333333p+2, 0x1.6666666666667p+1, -0x1.6666666666667p+2, 0x1.0cccccccccccdp+2, 0x1.3333333333334p+1, -0x1.3333333333334p+2, 0x1.cccccccccccccp+1, 0x1.0000000000000p+1, -0x1.0000000000000p+2, 0x1.8000000000000p+1, 0x1.999999999999ap+0, -0x1.999999999999ap+1, 0x1.3333333333333p+1, 0x1.3333333333334p+0, -0x1.3333333333334p+1, 0x1.cccccccccccccp+0, 0x1.999999999999ap-1, -0x1.999999999999ap+0, 0x1.3333333333333p+0, 0x1.999999999999ap-2, -0x1.999999999999ap-1, 0x1.3333333333333p-1,
};

pub const u_expected = [_]f64{
    -0x1.ffffffe100230p-2, 0x1.ffffffff5d1fap-2, -0x1.fffffea369173p-1, -0x1.ffffffe1620d6p-2, 0x1.ffffffffa9c5ap-2, -0x1.fffffea4e477bp-1, -0x1.ffffffe1eec77p-2, 0x1.ffffffffd4132p-2, -0x1.fffffea7ac082p-1, -0x1.ffffffe2afd00p-2, 0x1.ffffffffecdaap-2, -0x1.fffffeabc2799p-1, -0x1.ffffffe3acaa0p-2, 0x1.fffffffffe02ap-2, -0x1.fffffeb128545p-1, -0x1.ffffffe4bbed8p-2, 0x1.00000000072fep-1, -0x1.fffffeb7dcdb9p-1, -0x1.ffffffe5cd8e3p-2, 0x1.0000000012390p-1, -0x1.fffffebfa41b7p-1, -0x1.ffffffe726fa1p-2, 0x1.0000000020336p-1, -0x1.fffffec84e989p-1, -0x1.a08ab9368097cp-2, 0x1.ffffffffa116ap-2, -0x1.fffffed32137ep-1, -0x1.5b1ec987ecfbdp-3, 0x1.0000000041134p-1, -0x1.fffee5a270874p-1,
};
