// runtime/tests/emosqp.zig — the OSQP codegen static solver driven from Zig.
//
// The generated code (runtime/codegen/emosqp/) bakes the base MPC problem into
// a statically-allocated OSQPSolver global — no malloc, no libosqp dependency.
// This test updates the linear cost q (the only per-tick input for MPC) and
// compares the solution against the Python oracle.
//
// Generated by scripts/gen_emosqp_test.py — DO NOT EDIT.

const std = @import("std");
const c = @cImport({ @cInclude("osqp.h"); });

// The statically-allocated solver from workspace.c.
extern var solver: c.OSQPSolver;

const n_vars = 30;

// q = Fᵀ x₀ for the sample state x₀ = [0.1, -0.2, 0.3].
const q = [_]c.OSQPFloat{
    4, -8, 6, 3.6000000000000001, -7.2000000000000002, 5.3999999999999995, 3.2000000000000002, -6.4000000000000004,
    4.7999999999999998, 2.8000000000000003, -5.6000000000000005, 4.2000000000000002, 2.4000000000000004, -4.8000000000000007, 3.5999999999999996, 2,
    -4, 3, 1.6000000000000001, -3.2000000000000002, 2.3999999999999999, 1.2000000000000002, -2.4000000000000004, 1.7999999999999998,
    0.80000000000000004, -1.6000000000000001, 1.2, 0.40000000000000002, -0.80000000000000004, 0.59999999999999998,
};

// Expected solution from the Python oracle (same OSQP algorithm, eps=1e-06).
const u_expected = [_]f64{
    -0.4999999981955936, 0.49999999996296618, -0.99999995941884234, -0.49999999821785701, 0.49999999998039402, -0.99999995959136301, -0.49999999824985458, 0.49999999999001254,
    -0.99999995991494495, -0.49999999829374531, 0.4999999999956467, -0.99999996039081218, -0.4999999983512371, 0.49999999999954758, -0.99999996101920685, -0.49999999841291531,
    0.50000000000326827, -0.99999996179979356, -0.49999999847513105, 0.5000000000082867, -0.999999962705309, -0.49999999855367078, 0.50000000001464318, -0.99999996371416089,
    -0.40677918810992941, 0.4999999999784196, -0.99999996497409405, -0.16949231573164339, 0.50000000002959277, -0.99999158485321837,
};

test "codegen static solver matches python oracle" {
    // Update the linear cost (the only per-tick input for MPC), then solve.
    const rc = c.osqp_update_data_vec(&solver, &q, null, null);
    try std.testing.expectEqual(@as(c.OSQPInt, 0), rc);

    _ = c.osqp_solve(&solver);
    const status = solver.info.*.status_val;
    try std.testing.expectEqual(@as(c.OSQPInt, 1), status); // OSQP_SOLVED

    const x = solver.solution.*.x;
    for (0..n_vars) |j| {
        try std.testing.expectApproxEqAbs(u_expected[j], x[j], 1e-3);
    }
}
