// Generated by shinro.codegen.lower_zig — DO NOT EDIT.
// A ComposedGraph serialized as a comptime data table.

pub const Op = enum {
    cst, inp, out, matmul, add, sub, mul, div, ne, neg,
    transpose, inv, reshape, clip, where_op, any,
    copy, tanh, relu, exp, argmax, one_hot, slice,
    sin, cos, stack, solve_qp,
};

pub const Node = struct {
    op: Op,
    inputs: []const usize,
    rows: usize,
    cols: usize,
    aux: usize,
    vec: bool,
};

pub const buf_len = 120;
pub const has_solve_qp = false;
pub const n_outputs = 1;

pub const offsets = [_]usize{
    0, 3, 6, 9, 12, 15, 18, 27, 30, 39, 42, 45, 54, 57, 66, 69, 72, 75, 84, 87, 90, 93, 96, 105, 108, 111, 114, 117,
};

pub const nodes = [_]Node{
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 3, .vec = true },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 6, .vec = true },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 9, .vec = false },
    .{ .op = .reshape, .inputs = &.{0}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .reshape, .inputs = &.{2}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .matmul, .inputs = &.{6, 3}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 9, .vec = false },
    .{ .op = .matmul, .inputs = &.{8, 5}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .add, .inputs = &.{7, 9}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 18, .vec = false },
    .{ .op = .matmul, .inputs = &.{11, 10}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 27, .vec = false },
    .{ .op = .matmul, .inputs = &.{13, 5}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .add, .inputs = &.{12, 14}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .sub, .inputs = &.{4, 15}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 36, .vec = false },
    .{ .op = .matmul, .inputs = &.{17, 16}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .add, .inputs = &.{10, 18}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .reshape, .inputs = &.{19}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .sub, .inputs = &.{1, 20}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 45, .vec = false },
    .{ .op = .matmul, .inputs = &.{22, 21}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .clip, .inputs = &.{23}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .out, .inputs = &.{24}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .out, .inputs = &.{19}, .rows = 3, .cols = 1, .aux = 1, .vec = false },
    .{ .op = .out, .inputs = &.{24}, .rows = 3, .cols = 1, .aux = 2, .vec = true },
};

pub const const_blob = [_]f64{
    0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.47ae147ae147bp-6, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-6, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-6, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.999999999999ap-1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.999999999999ap-1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.999999999999ap-1, 0x1.72a8f38fccafdp+4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.72a8f38fccafdp+4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.1e9b2675a6625p+4,
};

pub const clip_lo = [_]f64{-0x1.0000000000000p-1, -0x1.0000000000000p-1, -0x1.0000000000000p+0};
pub const clip_hi = [_]f64{0x1.0000000000000p-1, 0x1.0000000000000p-1, 0x1.0000000000000p+0};

pub const output_offsets = [_]usize{0};
pub const state_offsets = [_]usize{0, 3};

