// Generated by shinro.codegen.lower_zig — DO NOT EDIT.
// A ComposedGraph serialized as a comptime data table.

pub const Op = enum {
    cst, cst_f32, inp, out, matmul, add, sub, mul, div, ne, neg,
    transpose, inv, reshape, clip, where_op, any,
    copy, tanh, relu, exp, argmax, one_hot, slice,
    sin, cos, stack, solve_qp,
    abs, sign, pow, lt, min, gemm, sigmoid, softmax, gelu, elu, layernorm,
    lstm, gru, rnn,
    concat, gather, sqrt, log, mod, leaky_relu,
};

pub const Node = struct {
    op: Op,
    inputs: []const usize,
    rows: usize,
    cols: usize,
    aux: usize,
    vec: bool,
};

pub const buf_len = 192;
pub const has_solve_qp = false;
pub const n_outputs = 1;

pub const offsets = [_]usize{
    0, 3, 6, 9, 12, 21, 24, 27, 27, 30, 30, 33, 36, 36, 45, 45, 54, 54, 63, 63, 72, 72, 81, 81, 90, 90, 99, 108, 117, 117, 120, 120, 123, 126, 129, 132, 135, 135, 135, 144, 153, 162, 165, 168, 168, 171, 174, 177, 180, 189,
};

pub const nodes = [_]Node{
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 3, .vec = true },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 6, .vec = true },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 9, .vec = false },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 12, .vec = false },
    .{ .op = .reshape, .inputs = &.{0}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .reshape, .inputs = &.{2}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .matmul, .inputs = &.{7, 3}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 9, .vec = false },
    .{ .op = .matmul, .inputs = &.{9, 6}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .add, .inputs = &.{8, 10}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 18, .vec = false },
    .{ .op = .matmul, .inputs = &.{12, 4}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 27, .vec = false },
    .{ .op = .matmul, .inputs = &.{13, 14}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 36, .vec = false },
    .{ .op = .add, .inputs = &.{15, 16}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 45, .vec = false },
    .{ .op = .matmul, .inputs = &.{18, 17}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 54, .vec = false },
    .{ .op = .matmul, .inputs = &.{19, 20}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 63, .vec = false },
    .{ .op = .add, .inputs = &.{21, 22}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 72, .vec = false },
    .{ .op = .matmul, .inputs = &.{17, 24}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .inv, .inputs = &.{23}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .matmul, .inputs = &.{25, 26}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 81, .vec = false },
    .{ .op = .matmul, .inputs = &.{28, 11}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 90, .vec = false },
    .{ .op = .matmul, .inputs = &.{30, 6}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .add, .inputs = &.{29, 31}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .sub, .inputs = &.{5, 32}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .matmul, .inputs = &.{27, 33}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .add, .inputs = &.{11, 34}, .rows = 3, .cols = 1, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 99, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 108, .vec = false },
    .{ .op = .matmul, .inputs = &.{27, 37}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .sub, .inputs = &.{36, 38}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .matmul, .inputs = &.{39, 17}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .reshape, .inputs = &.{35}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .sub, .inputs = &.{1, 41}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 117, .vec = false },
    .{ .op = .matmul, .inputs = &.{43, 42}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .clip, .inputs = &.{44}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .out, .inputs = &.{45}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .out, .inputs = &.{35}, .rows = 3, .cols = 1, .aux = 1, .vec = false },
    .{ .op = .out, .inputs = &.{40}, .rows = 3, .cols = 3, .aux = 2, .vec = false },
    .{ .op = .out, .inputs = &.{45}, .rows = 3, .cols = 1, .aux = 3, .vec = true },
};

pub const const_blob = [_]f64{
    0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.47ae147ae147bp-6, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-6, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-6, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.47ae147ae147bp-7, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-7, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-7, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.999999999999ap-4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.999999999999ap-4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.999999999999ap-4, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.72a8f38fccafdp+4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.72a8f38fccafdp+4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.1e9b2675a6625p+4,
};

pub const const_blob_f32 = [_]f32{};
pub const clip_lo = [_]f64{-0x1.0000000000000p-1, -0x1.0000000000000p-1, -0x1.0000000000000p+0};
pub const clip_hi = [_]f64{0x1.0000000000000p-1, 0x1.0000000000000p-1, 0x1.0000000000000p+0};
pub const gemm_alpha = [_]f64{};
pub const gemm_beta = [_]f64{};
pub const elu_alpha = [_]f64{};
pub const leaky_relu_alpha = [_]f64{};
pub const layernorm_eps = [_]f64{};
pub const output_offsets = [_]usize{0};
pub const state_offsets = [_]usize{0, 3, 12};

