// Generated by shinro.codegen.lower_zig — DO NOT EDIT.
// A ComposedGraph serialized as a comptime data table.

pub const Op = enum {
    cst, cst_f32, inp, out, matmul, add, sub, mul, div, ne, neg,
    transpose, inv, cholesky, reshape, clip, where_op, any,
    copy, tanh, relu, exp, argmax, one_hot, slice,
    sin, cos, stack, solve_qp,
    abs, sign, pow, lt, min, gemm, sigmoid, softmax, gelu, elu, layernorm,
    lstm, gru, rnn,
    concat, gather, sqrt, log, mod, leaky_relu,
};

pub const Node = struct {
    op: Op,
    inputs: []const usize,
    rows: usize,
    cols: usize,
    aux: usize,
    vec: bool,
};

pub const buf_len = 183;
pub const has_solve_qp = false;
pub const n_outputs = 1;

pub const offsets = [_]usize{
    0, 3, 6, 9, 12, 21, 21, 24, 24, 27, 30, 30, 39, 39, 48, 48, 57, 57, 66, 66, 75, 75, 84, 84, 93, 102, 111, 111, 114, 114, 117, 120, 123, 126, 129, 129, 129, 138, 147, 156, 159, 159, 162, 165, 168, 171, 180,
};

pub const nodes = [_]Node{
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 3, .vec = true },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 6, .vec = true },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 9, .vec = true },
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 12, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .matmul, .inputs = &.{5, 3}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 9, .vec = false },
    .{ .op = .matmul, .inputs = &.{7, 2}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .add, .inputs = &.{6, 8}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 18, .vec = false },
    .{ .op = .matmul, .inputs = &.{10, 4}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 27, .vec = false },
    .{ .op = .matmul, .inputs = &.{11, 12}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 36, .vec = false },
    .{ .op = .add, .inputs = &.{13, 14}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 45, .vec = false },
    .{ .op = .matmul, .inputs = &.{16, 15}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 54, .vec = false },
    .{ .op = .matmul, .inputs = &.{17, 18}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 63, .vec = false },
    .{ .op = .add, .inputs = &.{19, 20}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 72, .vec = false },
    .{ .op = .matmul, .inputs = &.{15, 22}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .inv, .inputs = &.{21}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .matmul, .inputs = &.{23, 24}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 81, .vec = false },
    .{ .op = .matmul, .inputs = &.{26, 9}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 90, .vec = false },
    .{ .op = .matmul, .inputs = &.{28, 2}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .add, .inputs = &.{27, 29}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .sub, .inputs = &.{0, 30}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .matmul, .inputs = &.{25, 31}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .add, .inputs = &.{9, 32}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 99, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 108, .vec = false },
    .{ .op = .matmul, .inputs = &.{25, 35}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .sub, .inputs = &.{34, 36}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .matmul, .inputs = &.{37, 15}, .rows = 3, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .sub, .inputs = &.{1, 33}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 3, .aux = 117, .vec = false },
    .{ .op = .matmul, .inputs = &.{40, 39}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .clip, .inputs = &.{41}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .out, .inputs = &.{42}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .out, .inputs = &.{33}, .rows = 3, .cols = 1, .aux = 1, .vec = true },
    .{ .op = .out, .inputs = &.{38}, .rows = 3, .cols = 3, .aux = 2, .vec = false },
    .{ .op = .out, .inputs = &.{42}, .rows = 3, .cols = 1, .aux = 3, .vec = true },
};

pub const const_blob = [_]f64{
    0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.47ae147ae147bp-6, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-6, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-6, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.47ae147ae147bp-7, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-7, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.47ae147ae147bp-7, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.999999999999ap-4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.999999999999ap-4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.999999999999ap-4, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.72a8f38fccafdp+4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.72a8f38fccafdp+4, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.1e9b2675a6625p+4,
};

pub const const_blob_f32 = [_]f32{};
pub const clip_lo = [_]f64{-0x1.0000000000000p-1, -0x1.0000000000000p-1, -0x1.0000000000000p+0};
pub const clip_hi = [_]f64{0x1.0000000000000p-1, 0x1.0000000000000p-1, 0x1.0000000000000p+0};
pub const gemm_alpha = [_]f64{};
pub const gemm_beta = [_]f64{};
pub const elu_alpha = [_]f64{};
pub const leaky_relu_alpha = [_]f64{};
pub const layernorm_eps = [_]f64{};
pub const output_offsets = [_]usize{0};
pub const state_offsets = [_]usize{0, 3, 12};

