// runtime/lower.zig — comptime graph VM: walks the generated node table and
// specializes one step of the closed loop at compile time.
//
// This is the Zig mirror of interpreter.py's dispatch loop. The graph data
// (op enum, inputs, shapes) is generated by shinro.codegen.lower_zig into
// graph_data.zig; the *code* here is handwritten once and never regenerated.
//
// The VM is comptime-specialized along one axis only: the outer `inline for`
// over the node table unrolls every node, so each node's op and shape are
// comptime constants and its slot is a fixed-size slice of one contiguous
// file-scope buffer — no heap, no runtime op dispatch. The element loops *inside*
// each node are runtime `for` loops over those comptime-known sizes. Unrolling
// them too emits one statement per element (~`buf_len` of them) and forces the
// compiler to optimize a single function of hundreds of thousands of
// instructions: minutes of compile and a `.so` that is ~2x the buffer in pure
// `.text`. Runtime element loops keep compile time and code size proportional
// to the node count, not the element count.
//
// C ABI (all flat, row-major f64 buffers; layout known to the host from the
// ComposedGraph port lists):
//   shinro_step(inputs, outputs, state_out)
//   - inputs:    host inputs packed in cg.inputs order (e.g. y, x_ref, u_prev
//                followed by the estimator's state_* recurrent ports)
//   - outputs:   packed in cg.outputs order
//   - state_out: packed in cg.state_outputs order (recurrent → next tick)

const std = @import("std");
// The generated graph and the bake's n_vars are anonymous imports wired by
// build.zig from -Dgraph / -Dsolver_dir (defaults: runtime/graph_data.zig and
// runtime/codegen/emosqp/solver_meta.zig).
const g = @import("graph_data");
// OSQP is deliberately conditional: the generated graph declares whether it
// contains a .solve_qp node. Non-QP graphs (LQR, PID, ...) build without the
// OSQP C sources, headers, or solver_meta module at all.
const sm = if (g.has_solve_qp) @import("solver_meta") else struct {};
const la = @import("linalg.zig");
const qp = if (g.has_solve_qp) @import("qp.zig") else struct {};

/// Per-tick workspace: every node's output slot is a slice of `workspace`,
/// addressed by `g.offsets`. Declared at file scope rather than as a local in
/// `shinro_step` so its size — `g.buf_len` f64, tens of MiB for large policies
/// — does not have to fit on the caller's stack (a stack-local copy overflows
/// the default 16 MiB stack past roughly 500k parameters).
///
/// This is process-global mutable state, so `shinro_step` is **not reentrant
/// or thread-safe**: one call must finish before the next starts. That is the
/// deployment model (one control loop, one tick at a time) and matches the QP
/// path's statically-allocated `solver` global. The graph writes every slot
/// before it is read, so the buffer needs no initialization.
var workspace: [g.buf_len]f64 align(16) = undefined;

/// Run one tick of the closed-loop step through the generated node table.
///
/// The C-ABI entry point (exported as `shinro_step`) that the host calls once
/// per control tick. All buffers are flat, row-major f64; their layout is
/// known to the host from the ComposedGraph port lists:
///
/// - `inputs`: host inputs packed in `cg.inputs` order (e.g. `y`, `x_ref`,
///   `u_prev` followed by the estimator's `state_*` recurrent ports)
/// - `outputs`: packed in `cg.outputs` order
/// - `state_out`: packed in `cg.state_outputs` order (recurrent → next tick)
///
/// The `inline for` over `g.nodes` unrolls the whole node table at compile
/// time, so every node's op and shape are comptime constants and every array
/// is a fixed-size slice of the single file-scope `workspace` — no heap, no
/// runtime op dispatch. The element loops *within* each node are runtime loops over
/// those comptime-known sizes, so code size and compile time scale with the
/// node count rather than with `buf_len`.
///
/// Not reentrant or thread-safe: writes go to the shared file-scope
/// `workspace` (see its declaration). Callers run one tick at a time.
///
/// Args:
///     inputs: Flat buffer of this tick's host inputs.
///     outputs: Flat buffer where this tick's output ports are written.
///     state_out: Flat buffer where this tick's recurrent state outputs are
///         written (fed back as state inputs next tick).
export fn shinro_step(inputs: [*]const f64, outputs: [*]f64, state_out: [*]f64) void {
    @setEvalBranchQuota(1_000_000);

    inline for (g.nodes, 0..) |node, i| {
        const out = workspace[g.offsets[i]..][0 .. node.rows * node.cols];

        switch (node.op) {
            .cst => {
                for (0..node.rows * node.cols) |j| out[j] = g.const_blob[node.aux + j];
            },
            .inp => {
                for (0..node.rows * node.cols) |j| out[j] = inputs[node.aux + j];
            },
            .out => {
                const src = node_input(g.nodes[0..], node, &workspace);
                if (node.aux < g.n_outputs) {
                    for (0..node.rows * node.cols) |j| outputs[g.output_offsets[node.aux] + j] = src[j];
                } else {
                    for (0..node.rows * node.cols) |j| state_out[g.state_offsets[node.aux - g.n_outputs] + j] = src[j];
                }
            },
            .matmul => {
                const a = node_input(g.nodes[0..], node, &workspace);
                const b = node_input_at(g.nodes[0..], node.inputs[1], &workspace);
                const left = g.nodes[node.inputs[0]];
                const right = g.nodes[node.inputs[1]];
                if (left.vec) {
                    // vecmat: (k,) @ (k, n) -> (n,) — a genuinely 1-D left operand
                    const r = la.vecmat(left.rows, node.rows, a, b);
                    for (0..node.rows * node.cols) |j| out[j] = r[j];
                } else if (right.vec) {
                    // matvec: (m, k) @ (k,) -> (m,)
                    const r = la.matvec(node.rows, right.rows, a, b);
                    for (0..node.rows * node.cols) |j| out[j] = r[j];
                } else {
                    // matmul: (m, k) @ (k, n) -> (m, n); also covers (m,1)@(1,n) (k=1)
                    const r = la.matmul(node.rows, left.cols, node.cols, a, b);
                    for (0..node.rows * node.cols) |j| out[j] = r[j];
                }
            },
            .add => ew2(g.nodes[0..], node, i, &workspace, .add),
            .sub => ew2(g.nodes[0..], node, i, &workspace, .sub),
            .mul => ew2(g.nodes[0..], node, i, &workspace, .mul),
            .div => ew2(g.nodes[0..], node, i, &workspace, .div),
            .ne => ew2(g.nodes[0..], node, i, &workspace, .ne),
            .lt => ew2(g.nodes[0..], node, i, &workspace, .lt),
            .pow => ew2(g.nodes[0..], node, i, &workspace, .pow),
            .neg => {
                const s = node_input(g.nodes[0..], node, &workspace);
                for (0..node.rows * node.cols) |j| out[j] = -s[j];
            },
            .abs => {
                const s = node_input(g.nodes[0..], node, &workspace);
                for (0..node.rows * node.cols) |j| out[j] = @abs(s[j]);
            },
            .sign => {
                // Matches np.sign: -1 / 0 / +1 (0 maps to 0, not +1).
                const s = node_input(g.nodes[0..], node, &workspace);
                for (0..node.rows * node.cols) |j| {
                    out[j] = if (s[j] > 0.0) 1.0 else if (s[j] < 0.0) -1.0 else 0.0;
                }
            },
            .transpose => {
                const s = node_input(g.nodes[0..], node, &workspace);
                // True 2-D transpose: out (node.rows, node.cols) = src.T, so
                // out[i][j] = src[j][i] — flat out[i*node.cols + j] =
                // s[j*src.cols + i]. (The old form baked in the square case's
                // stride symmetry and silently scrambled non-square inputs.)
                for (0..node.rows) |oi| {
                    for (0..node.cols) |oj| out[oi * node.cols + oj] = s[oj * g.nodes[node.inputs[0]].cols + oi];
                }
            },
            .inv => {
                const s = node_input(g.nodes[0..], node, &workspace);
                const r = la.inv(node.rows, s);
                for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .reshape => {
                const s = node_input(g.nodes[0..], node, &workspace);
                for (0..node.rows * node.cols) |j| out[j] = s[j];
            },
            .clip => {
                const s = node_input(g.nodes[0..], node, &workspace);
                for (0..node.rows * node.cols) |j| {
                    out[j] = std.math.clamp(s[j], g.clip_lo[node.aux + j], g.clip_hi[node.aux + j]);
                }
            },
            .where_op => {
                const cond = node_input(g.nodes[0..], node, &workspace);
                const a = node_input_at(g.nodes[0..], node.inputs[1], &workspace);
                const b = node_input_at(g.nodes[0..], node.inputs[2], &workspace);
                const cond_n = g.nodes[node.inputs[0]];
                const a_n = g.nodes[node.inputs[1]];
                const b_n = g.nodes[node.inputs[2]];
                for (0..node.rows) |oi| {
                    for (0..node.cols) |oj| {
                        const f = oi * node.cols + oj;
                        const c = cond[if (cond_n.rows * cond_n.cols == 1) 0 else f];
                        const av = a[bcast_flat(a_n, a_n.vec, node.rows, node.cols, oi, oj)];
                        const bv = b[bcast_flat(b_n, b_n.vec, node.rows, node.cols, oi, oj)];
                        out[f] = if (c != 0.0) av else bv;
                    }
                }
            },
            .any => {
                const s = node_input(g.nodes[0..], node, &workspace);
                var found = false;
                for (0..g.nodes[node.inputs[0]].rows * g.nodes[node.inputs[0]].cols) |j| {
                    if (s[j] != 0.0) found = true;
                }
                out[0] = if (found) 1.0 else 0.0;
            },
            // deterministic-policy ops (issue #13): elementwise maps, a
            // reduction (argmax), an expansion (one_hot), and shape glue
            // (copy / slice). None allocate — all iterate comptime-known
            // flat buffers. tanh/relu/exp preserve shape; argmax collapses
            // to a scalar (stored as f64 in the buffer); one_hot expands a
            // scalar index to a depth-row; copy/slice are flat copies with
            // slice's `aux` holding the input offset.
            .copy => {
                const s = node_input(g.nodes[0..], node, &workspace);
                for (0..node.rows * node.cols) |j| out[j] = s[j];
            },
            .tanh => {
                const s = node_input(g.nodes[0..], node, &workspace);
                const r = la.tanh(node.rows * node.cols, s);
                for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .relu => {
                const s = node_input(g.nodes[0..], node, &workspace);
                const r = la.relu(node.rows * node.cols, s);
                for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .sigmoid => {
                const s = node_input(g.nodes[0..], node, &workspace);
                const r = la.sigmoid(node.rows * node.cols, s);
                for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .exp => {
                const s = node_input(g.nodes[0..], node, &workspace);
                const r = la.elementwise_exponential(node.rows * node.cols, s);
                for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .sin => {
                const s = node_input(g.nodes[0..], node, &workspace);
                const r = la.sin_vec(node.rows * node.cols, s);
                for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .cos => {
                const s = node_input(g.nodes[0..], node, &workspace);
                const r = la.cos_vec(node.rows * node.cols, s);
                for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .argmax => {
                const s = node_input(g.nodes[0..], node, &workspace);
                const n_in = g.nodes[node.inputs[0]].rows * g.nodes[node.inputs[0]].cols;
                const idx = la.argmax(n_in, s);
                out[0] = @floatFromInt(idx);
            },
            .min => {
                // Minimum reduction; aux selects numpy's axis (0 = None / full,
                // 1 = axis 0 down columns, 2 = axis 1 across rows). The output
                // shape was fixed at trace time, so rows*cols is the exact
                // element count the chosen reduction produces.
                const s = node_input(g.nodes[0..], node, &workspace);
                const src = g.nodes[node.inputs[0]];
                if (node.aux == 0) {
                    const r = la.min_all(src.rows * src.cols, s);
                    out[0] = r[0];
                } else if (node.aux == 1) {
                    const r = la.min_axis0(src.rows, src.cols, s);
                    for (0..node.rows * node.cols) |j| out[j] = r[j];
                } else {
                    const r = la.min_axis1(src.rows, src.cols, s);
                    for (0..node.rows * node.cols) |j| out[j] = r[j];
                }
            },
            .one_hot => {
                const s = node_input(g.nodes[0..], node, &workspace);
                const idx: usize = @intFromFloat(s[0]);
                const r = la.onehot(node.rows, idx);
                for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            .slice => {
                const s = node_input(g.nodes[0..], node, &workspace);
                const src = g.nodes[node.inputs[0]];
                if (src.vec) {
                    // 1-D source: aux is the flat element offset.
                    for (0..node.rows * node.cols) |j| out[j] = s[node.aux + j];
                } else {
                    // 2-D source: the interpreter slices ROWS (x[start:stop]
                    // along axis 0), so out[i][j] = src[start + i][j].
                    for (0..node.rows) |oi| {
                        for (0..node.cols) |oj| out[oi * node.cols + oj] = s[(node.aux + oi) * src.cols + oj];
                    }
                }
            },
            // stack([a, b, ...]) along a new leading axis (numpy axis=0). Each
            // input contributes its flat length to consecutive output rows; all
            // inputs share the same shape (enforced at trace time), so the
            // output flat length is n_inputs * in_len == node.rows * node.cols.
            .stack => {
                for (node.inputs, 0..) |inp_idx, row| {
                    const src = node_input_at(g.nodes[0..], inp_idx, &workspace);
                    const in_len = g.nodes[inp_idx].rows * g.nodes[inp_idx].cols;
                    for (0..in_len) |j| out[row * in_len + j] = src[j];
                }
            },
            // .gemm — fused dense layer: out = alpha*(A@B') + beta*C in one
            // pass (linalg.gemm). Covers the ONNX importer's Gemm: the
            // contraction, the alpha/beta scales, the optional transB (torch
            // nn.Linear weight layout, read by striding rather than
            // materializing a transpose), and the bias add are a single kernel.
            // alpha/beta are baked into g.gemm_alpha/gemm_beta; aux packs the
            // table index in the upper bits and the transB flag in bit 0. A
            // 1-D activation (vec) is treated as a single row (m = 1).
            .gemm => {
                const a = node_input(g.nodes[0..], node, &workspace);
                const b = node_input_at(g.nodes[0..], node.inputs[1], &workspace);
                const c = node_input_at(g.nodes[0..], node.inputs[2], &workspace);
                const a_n = g.nodes[node.inputs[0]];
                const c_n = g.nodes[node.inputs[2]];
                const r = la.gemm(
                    if (node.vec) 1 else node.rows,
                    if (a_n.vec) a_n.rows else a_n.cols,
                    if (node.vec) node.rows else node.cols,
                    g.gemm_alpha[node.aux / 2],
                    g.gemm_beta[node.aux / 2],
                    node.aux % 2 == 1,
                    a,
                    b,
                    c,
                    c_n.rows * c_n.cols,
                );
                for (0..node.rows * node.cols) |j| out[j] = r[j];
            },
            // .solve_qp — the convergence-iterative MPC op. The problem data
            // (P, A, l, u) and the pre-factorized KKT matrix are baked into the
            // statically-allocated `solver` global by the codegen C
            // (runtime/codegen/emosqp/). Only the linear cost q changes per
            // tick: it is read from the node's input slot and written in via
            // osqp_update_data_vec, then the full solution lands in this
            // node's output slot (u[:m] is sliced out by a downstream op).
            // The node's output size must match the baked problem's n_vars —
            // enforced here at compile time, so a graph lowered against the
            // wrong bake refuses to build instead of silently linking a
            // shape-mismatched solver.
            .solve_qp => {
                comptime {
                    if (node.rows * node.cols != sm.n_vars) {
                        @compileError("graph solve_qp node output size (" ++
                            std.fmt.comptimePrint("{d}", .{node.rows * node.cols}) ++
                            ") does not match baked solver n_vars (" ++
                            std.fmt.comptimePrint("{d}", .{sm.n_vars}) ++
                            ") — rebuild with the matching -Dsolver_dir");
                    }
                }
                const q_vec = node_input(g.nodes[0..], node, &workspace);
                qp.solve_qp(q_vec, out);
            },
        }
    }
}

// --- helpers ---------------------------------------------------------------

const BinOp = enum { add, sub, mul, div, ne, lt, pow };

/// Flat index of operand element (i, j) under numpy broadcasting.
///
/// The tracer only captures numpy-valid broadcasts, so at comptime the
/// operand shape must fall into one of: scalar, same shape, (1, m) row
/// broadcast, (n, 1) column broadcast, or a genuinely 1-D (`vec`) operand
/// right-aligned to the output's columns. The old code only handled
/// same-shape and size-1 — a (1, m)-against-(n, m) add or a scalar `where`
/// branch read out of bounds (panic in debug, garbage in release).
inline fn bcast_flat(op: g.Node, op_vec: bool, out_r: usize, out_c: usize, i: usize, j: usize) usize {
    if (op.rows * op.cols == 1) return 0; // scalar broadcast
    if (op_vec and op.rows == out_c) return j; // (m,) right-aligns to the last axis
    if (op.rows == out_r and op.cols == out_c) return i * out_c + j; // same shape
    if (op.rows == 1 and op.cols == out_c) return j; // (1, m) row broadcast
    if (op.cols == 1 and op.rows == out_r) return i; // (n, 1) col broadcast
    return i * out_c + j; // unreachable for numpy-valid traces
}

/// Elementwise binary op with numpy broadcasting.
///
/// Each operand is indexed through `bcast_flat`: same shape, scalar,
/// (1, m) row, (n, 1) column, or a 1-D (`vec`) operand right-aligned to the
/// output's columns. `inline` so the comptime-known node shapes and the `op`
/// tag constant-fold into the runtime element loop (the bounds stay comptime
/// constants, but the loop itself is not unrolled).
///
/// Args:
///     nodes: The full generated node table (for shape lookup).
///     node: The current add/sub/mul/div/ne node.
///     self_idx: The node's index in `nodes` (its buffer offset).
///     buf: The shared step buffer (written at the node's offset).
///     op: Which binary op to apply (add, sub, mul, div, ne, lt, pow).
inline fn ew2(nodes: []const g.Node, node: g.Node, self_idx: usize, buf: *[g.buf_len]f64, op: BinOp) void {
    const a = node_input_at(nodes, node.inputs[0], buf);
    const b = node_input_at(nodes, node.inputs[1], buf);
    const a_n = nodes[node.inputs[0]];
    const b_n = nodes[node.inputs[1]];
    var out = buf.*[g.offsets[self_idx]..][0 .. node.rows * node.cols];
    for (0..node.rows) |i| {
        for (0..node.cols) |j| {
            const av = a[bcast_flat(a_n, a_n.vec, node.rows, node.cols, i, j)];
            const bv = b[bcast_flat(b_n, b_n.vec, node.rows, node.cols, i, j)];
            out[i * node.cols + j] = switch (op) {
                .add => av + bv,
                .sub => av - bv,
                .mul => av * bv,
                .div => av / bv,
                // Inequality as a 1.0/0.0 flag — the graph's boolean repr,
                // consumed by where_op downstream (e.g. PID anti-windup).
                .ne => if (av != bv) 1.0 else 0.0,
                // Ordered comparison as a 1.0/0.0 flag — `ne`'s sibling, the
                // predicate behind threshold guards (e.g. SMC's near-zero
                // |c^T g| controllability check).
                .lt => if (av < bv) 1.0 else 0.0,
                // numpy's power semantics (np.power); SMC raises the abs'd
                // sliding variable to a fractional alpha, so no negative base.
                .pow => std.math.pow(f64, av, bv),
            };
        }
    }
}

/// Read a node's first input from the shared buffer.
///
/// Args:
///     nodes: The full generated node table (for shape lookup).
///     node: The consumer node whose first input to read.
///     buf: The shared step buffer.
///
/// Returns:
///     A fixed-length slice of `buf` covering the input node's slot.
fn node_input(nodes: []const g.Node, node: g.Node, buf: *[g.buf_len]f64) []const f64 {
    return node_input_at(nodes, node.inputs[0], buf);
}

/// Read an arbitrary node's output slot from the buffer by node index.
///
/// Args:
///     nodes: The full generated node table (for shape lookup).
///     idx: The node index whose output to read.
///     buf: The shared step buffer.
///
/// Returns:
///     A fixed-length slice of `buf` covering node `idx`'s `rows*cols` f64s.
fn node_input_at(nodes: []const g.Node, idx: usize, buf: *[g.buf_len]f64) []const f64 {
    return buf.*[g.offsets[idx]..][0 .. nodes[idx].rows * nodes[idx].cols];
}
