// Test fixture `toy_lstm` — committed toy LSTM, H=4 (fused LSTM cell + live state).
// Generated by scripts/gen_lower_fixtures.py from /mnt/E/github-projects/shinro-python-modules/tests/fixtures/models/toy_lstm.onnx — DO NOT EDIT.
const std = @import("std");

pub const Op = enum {
    cst,
    cst_f32,
    inp,
    out,
    matmul,
    add,
    sub,
    mul,
    div,
    ne,
    neg,
    transpose,
    inv,
    reshape,
    clip,
    where_op,
    any,
    copy,
    tanh,
    relu,
    exp,
    argmax,
    one_hot,
    slice,
    sin,
    cos,
    stack,
    solve_qp,
    abs,
    sign,
    pow,
    lt,
    min,
    gemm,
    sigmoid,
    softmax,
    gelu,
    elu,
    layernorm,
    lstm,
    gru,
    rnn,
    concat,
    gather,
    sqrt,
    log,
    mod,
    leaky_relu,
};

pub const Node = struct {
    op: Op,
    inputs: []const usize,
    rows: usize,
    cols: usize,
    aux: usize,
    vec: bool,
};

pub const buf_len = 51;
pub const has_solve_qp = false;
pub const n_outputs = 1;

pub const offsets = [_]usize{
    0, 3, 3, 6, 9, 13, 13, 13, 13, 17, 25, 29, 37, 37, 41, 41, 43, 45, 45, 47, 47, 49,
};

pub const nodes = [_]Node{
    .{ .op = .inp, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .cst, .inputs = &.{}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .reshape, .inputs = &.{0}, .rows = 1, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .reshape, .inputs = &.{2}, .rows = 3, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .inp, .inputs = &.{}, .rows = 4, .cols = 1, .aux = 3, .vec = true },
    .{ .op = .cst_f32, .inputs = &.{}, .rows = 16, .cols = 3, .aux = 0, .vec = false },
    .{ .op = .cst_f32, .inputs = &.{}, .rows = 16, .cols = 4, .aux = 48, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 32, .cols = 1, .aux = 3, .vec = true },
    .{ .op = .inp, .inputs = &.{}, .rows = 4, .cols = 1, .aux = 7, .vec = true },
    .{ .op = .lstm, .inputs = &.{ 3, 5, 6, 7, 4, 8 }, .rows = 8, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .slice, .inputs = &.{9}, .rows = 4, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .out, .inputs = &.{9}, .rows = 8, .cols = 1, .aux = 1, .vec = true },
    .{ .op = .cst, .inputs = &.{}, .rows = 2, .cols = 1, .aux = 35, .vec = true },
    .{ .op = .reshape, .inputs = &.{10}, .rows = 1, .cols = 4, .aux = 0, .vec = false },
    .{ .op = .cst, .inputs = &.{}, .rows = 4, .cols = 2, .aux = 37, .vec = false },
    .{ .op = .matmul, .inputs = &.{ 13, 14 }, .rows = 1, .cols = 2, .aux = 0, .vec = false },
    .{ .op = .reshape, .inputs = &.{15}, .rows = 2, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .cst, .inputs = &.{}, .rows = 1, .cols = 1, .aux = 45, .vec = false },
    .{ .op = .mul, .inputs = &.{ 16, 17 }, .rows = 2, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .cst, .inputs = &.{}, .rows = 1, .cols = 1, .aux = 46, .vec = false },
    .{ .op = .add, .inputs = &.{ 18, 19 }, .rows = 2, .cols = 1, .aux = 0, .vec = true },
    .{ .op = .out, .inputs = &.{20}, .rows = 2, .cols = 1, .aux = 0, .vec = true },
};

pub const const_blob = [_]f64{
    0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x1.8000000000000p+1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+2, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.0000000000000p+0, 0x0.0p+0,
};

const _weights: [448]u8 align(@alignOf(f32)) = @embedFile("toy_lstm_weights.bin").*;
pub const const_blob_f32: []const f32 = std.mem.bytesAsSlice(f32, &_weights);
pub const clip_lo = [_]f64{};
pub const clip_hi = [_]f64{};
pub const gemm_alpha = [_]f64{};
pub const gemm_beta = [_]f64{};
pub const elu_alpha = [_]f64{};
pub const leaky_relu_alpha = [_]f64{};
pub const layernorm_eps = [_]f64{};
pub const output_offsets = [_]usize{0};
pub const state_offsets = [_]usize{0};
