"""Bake the OSQP codegen static solver for one MPC problem.

The comptime VM's ``.solve_qp`` op links a statically-allocated OSQP solver
whose problem data (P, A, l, u) is baked into fixed-size C arrays — no malloc,
no libosqp dependency. Only the linear cost ``q`` changes per tick (written via
``osqp_update_data_vec``), so the solver is generated once per problem.

:func:`bake_emosqp` is the generator. ``scripts/gen_emosqp_test.py`` wraps it to
also emit the Zig oracle vectors; ``shinro build`` calls it on demand when a
scenario declares ``[compile].solver = "emosqp"`` (see
:mod:`shinro.codegen.scenario_build` for the wiring and :func:`bake_is_current`
for the reuse check).

The generated tree is problem-specific: its ``n_vars`` is compiled into
fixed-size C arrays and comptime-checked against the graph's ``.solve_qp``
output size, so a graph and a bake must be a matched pair.

``osqp`` / ``scipy`` are imported lazily inside :func:`bake_emosqp` so that
merely importing the codegen schema (which needs :data:`SOLVERS` to validate a
``[compile].solver`` name) does not pull in the solver stack.

:data:`SOLVERS` maps a ``[compile].solver`` name to its baker; adding a second
solver is one registry entry.
"""

from __future__ import annotations

import hashlib
import re
import sys
from dataclasses import dataclass
from importlib.metadata import version
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

from shinro.factories.controller_factory import ControllerFactory
from shinro.utils.array_backend import NumpyBackend
from shinro.utils.config_resolver import resolve_config_path

if TYPE_CHECKING:
    from scipy import sparse

#: OSQP convergence tolerance. The codegen and the Python oracle both use it so
#: they converge to the same point (oracle B compares the .so against the
#: interpreter on the same problem).
EPS = 1e-6


@dataclass
class Bake:
    """The baked problem plus the data a caller may reuse for oracle vectors."""

    n_vars: int
    n_cons: int
    F: np.ndarray
    H: np.ndarray
    A: sparse.csc_matrix
    lb: np.ndarray
    ub: np.ndarray


def config_sha256(config_path: str) -> str:
    """Return the sha256 of a controller config's raw bytes (hermetic).

    Resolves the path the same way the factories do, so the hash covers exactly
    the file the controller was built from.
    """
    with open(resolve_config_path(config_path), "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def _solver_meta_text(config: str, n_vars: int, n_cons: int) -> str:
    return f"""// solver_meta.zig — Generated by shinro.codegen.bake — DO NOT EDIT.
// The baked solver's variable count. src/shinro/runtime/lower.zig comptime-checks that
// any graph containing a .solve_qp node matches this n_vars at build time.
// The remaining consts are provenance surfaced in the build manifest.

pub const n_vars: usize = {n_vars};
pub const n_cons: usize = {n_cons};
pub const eps: f64 = {EPS};
pub const config = "{config}";
pub const config_sha256 = "{config_sha256(config)}";
pub const python_version = "{sys.version.split()[0]}";
pub const numpy_version = "{version('numpy')}";
pub const scipy_version = "{version('scipy')}";
pub const osqp_version = "{version('osqp')}";
"""


def bake_emosqp(config: str, out_dir: str) -> Bake:
    """Generate the static OSQP solver for ``config`` into ``out_dir``.

    Writes the codegen tree (``workspace.c``, ``inc/``, ``src/``) and
    ``solver_meta.zig``. Does **not** touch the Zig oracle vectors — those are
    test data, the caller's job.

    Args:
        config: MPC controller TOML config path.
        out_dir: Directory to write the codegen solver tree (created if needed).

    Returns:
        A :class:`Bake` with ``n_vars``/``n_cons`` and the problem data (``ctrl``,
        ``H``, ``A``, ``lb``, ``ub``) so the caller can build oracle vectors
        without re-instantiating the controller.
    """
    import osqp
    from scipy import sparse

    ctrl = ControllerFactory(config).create(backend=NumpyBackend())
    F = np.asarray(ctrl.F, dtype=np.float64)
    H = np.asarray(ctrl.H, dtype=np.float64)
    A = ctrl.A_constraints.tocsc()
    lb = np.asarray(ctrl.lcons, dtype=np.float64)
    ub = np.asarray(ctrl.ucons, dtype=np.float64)

    # Baked with q=0; q is updated per tick (parameters="vectors").
    prob = osqp.OSQP()
    prob.setup(sparse.csc_matrix(H), np.zeros(H.shape[0]), A, lb, ub, warm_starting=True, verbose=False)
    prob.update_settings(eps_abs=EPS, eps_rel=EPS)
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    prob.codegen(out_dir, parameters="vectors", force_rewrite=True, printing_enable=False)

    (Path(out_dir) / "solver_meta.zig").write_text(_solver_meta_text(config, H.shape[0], A.shape[0]))
    return Bake(n_vars=H.shape[0], n_cons=A.shape[0], F=F, H=H, A=A, lb=lb, ub=ub)


_META_N_VARS = re.compile(r"pub const n_vars: usize = (\d+);")
_META_CONFIG_SHA = re.compile(r'pub const config_sha256 = "([0-9a-f]{64})";')


def bake_is_current(out_dir: str, n_vars: int, config: str) -> bool:
    """True when ``out_dir`` already holds a solver for this n_vars + config.

    Keys on the controller config's content sha, so editing the MPC config
    (Q/R/horizon) invalidates the bake instead of silently reusing it.
    """
    meta = Path(out_dir) / "solver_meta.zig"
    if not meta.exists():
        return False
    text = meta.read_text()
    m_vars = _META_N_VARS.search(text)
    m_sha = _META_CONFIG_SHA.search(text)
    return bool(m_vars and m_sha and int(m_vars.group(1)) == n_vars and m_sha.group(1) == config_sha256(config))


#: Registered solver bakers, keyed by a scenario's ``[compile].solver`` name.
SOLVERS = {"emosqp": bake_emosqp}
