"""Lower a :class:`~shinro.codegen.compose.ComposedGraph` to a Zig data table.

This is Option B of the lowering design: Python emits **data only** — the node
table, the packed constants, and the port layout — never Zig statements. The
actual program (the comptime graph VM) is handwritten once in
``runtime/lower.zig`` and specialized at compile time over this table.

The generated file ``runtime/graph_data.zig`` contains:

- ``nodes``: the flat list of :class:`Node` records — op enum + input ids +
  rows/cols + an ``aux`` index whose meaning depends on the op.
- ``offsets``: per-node buffer offset (node ``i`` owns ``rows*cols`` f64s at
  ``buf[offsets[i]..offsets[i]+rows*cols]``).
- ``buf_len``: total f64 buffer size for one step.
- ``const_blob``: all baked constants, one flat row-major f64 array.
- ``clip_lo``/``clip_hi``: clip bounds, one flat array each.
- ``n_outputs``, ``output_offsets``, ``state_offsets``: port packing into the
  C-ABI ``shinro_step(inputs, outputs, state_out)`` buffers.

Constants are emitted as Zig hex floats (``float.hex()``), which bit-exactly
round-trip the f64 the tracer baked in — the "fixed at compile time" property
holds across the language boundary.

Usage:

    from shinro.codegen.lower_zig import lower_zig
    lower_zig(composed, out_path="runtime/graph_data.zig")
"""

from __future__ import annotations

from shinro.codegen.compose import ComposedGraph
from shinro.codegen.tracing import Graph, Node


def lower_zig(cg: ComposedGraph, out_path: str = "runtime/graph_data.zig") -> None:
    """Serialize a composed graph into a Zig data table at ``out_path``."""
    g = cg.graph

    # --- buffer layout: each node owns a slot sized by its shape ---
    offsets: list[int] = []
    total = 0
    for n in g.nodes:
        offsets.append(total)
        total += _size(n.shape)
    buf_len = total

    # --- input port packing (cg.inputs order) ---
    input_offsets: dict[str, int] = {}
    acc = 0
    for name in cg.inputs:
        input_offsets[name] = acc
        acc += _input_size(g, name)

    # --- constants and clip bounds ---
    const_blob: list[float] = []
    const_offsets: dict[int, int] = {}
    clip_lo: list[float] = []
    clip_hi: list[float] = []
    clip_offsets: dict[int, int] = {}

    for i, node in enumerate(g.nodes):
        if node.op == "const":
            const_offsets[i] = len(const_blob)
            const_blob.extend(float(v) for v in node.attrs["value"].ravel())
        elif node.op == "clip":
            clip_offsets[i] = len(clip_lo)
            clip_lo.extend(float(v) for v in node.attrs["lo"].ravel())
            clip_hi.extend(float(v) for v in node.attrs["hi"].ravel())

    # --- output port packing: separate zero-indexed offsets per buffer ---
    # `outputs` and `state_out` are separate C-ABI buffers, so each needs its
    # own cumulative offset table starting at 0.
    output_offsets: list[int] = []
    acc = 0
    for name in cg.outputs:
        output_offsets.append(acc)
        acc += _output_size(g, name)
    state_offsets: list[int] = []
    acc = 0
    for name in cg.state_outputs:
        state_offsets.append(acc)
        acc += _output_size(g, name)

    lines: list[str] = []
    lines.append("// Generated by shinro.codegen.lower_zig — DO NOT EDIT.")
    lines.append("// A ComposedGraph serialized as a comptime data table.")
    lines.append("")
    lines.append("pub const Op = enum {")
    lines.append("    cst, inp, out, matmul, add, sub, mul, div, neg,")
    lines.append("    transpose, inv, reshape, clip, where_op, any,")
    lines.append("};")
    lines.append("")
    lines.append("pub const Node = struct {")
    lines.append("    op: Op,")
    lines.append("    inputs: []const usize,")
    lines.append("    rows: usize,")
    lines.append("    cols: usize,")
    lines.append("    aux: usize,")
    lines.append("};")
    lines.append("")
    lines.append(f"pub const buf_len = {buf_len};")
    lines.append(f"pub const n_outputs = {len(cg.outputs)};")
    lines.append("")
    lines.append("pub const offsets = [_]usize{")
    lines.append("    " + ", ".join(str(o) for o in offsets) + ",")
    lines.append("};")
    lines.append("")
    lines.append("pub const nodes = [_]Node{")
    for i, node in enumerate(g.nodes):
        lines.append("    " + _node_line(g, i, node, const_offsets, clip_offsets, input_offsets, cg.outputs, cg.state_outputs) + ",")
    lines.append("};")
    lines.append("")
    lines.append("pub const const_blob = [_]f64{")
    lines.append("    " + _zig_floats(const_blob) + ",")
    lines.append("};")
    lines.append("")
    lines.append("pub const clip_lo = [_]f64{" + _zig_floats(clip_lo) + "};")
    lines.append("pub const clip_hi = [_]f64{" + _zig_floats(clip_hi) + "};")
    lines.append("")
    lines.append("pub const output_offsets = [_]usize{" + ", ".join(str(o) for o in output_offsets) + "};")
    lines.append("pub const state_offsets = [_]usize{" + ", ".join(str(o) for o in state_offsets) + "};")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")


# ─── helpers ───────────────────────────────────────────────────────────────


def _node_line(
    g: Graph,
    i: int,
    node: Node,
    const_offsets: dict[int, int],
    clip_offsets: dict[int, int],
    input_offsets: dict[str, int],
    outputs: list[str],
    state_outputs: list[str],
) -> str:
    rows, cols = _rows_cols(node.shape)
    inputs = "&.{" + ", ".join(str(x) for x in node.inputs) + "}"
    op = node.op
    aux = 0

    if node.op == "const":
        op = "cst"
        aux = const_offsets[i]
    elif node.op == "input":
        op = "inp"
        aux = input_offsets[node.attrs["name"]]
    elif node.op == "output":
        op = "out"
        name = node.attrs["name"]
        if name in outputs:
            aux = outputs.index(name)
        else:
            # state outputs are offset by n_outputs in the VM's port switch.
            aux = len(outputs) + state_outputs.index(name)
    elif node.op == "where":
        op = "where_op"
    elif node.op == "clip":
        op = "clip"
        aux = clip_offsets[i]

    return f".{{ .op = .{op}, .inputs = {inputs}, .rows = {rows}, .cols = {cols}, .aux = {aux} }}"


def _input_size(g: Graph, name: str) -> int:
    for node in g.nodes:
        if node.op == "input" and node.attrs["name"] == name:
            return _size(node.shape)
    raise KeyError(f"input port '{name}' not found in graph")


def _output_size(g: Graph, name: str) -> int:
    for node in g.nodes:
        if node.op == "output" and node.attrs["name"] == name:
            return _size(node.shape)
    raise KeyError(f"output port '{name}' not found in graph")


def _size(shape: tuple[int, ...]) -> int:
    if not shape:
        return 1
    out = 1
    for d in shape:
        out *= d
    return out


def _rows_cols(shape: tuple[int, ...]) -> tuple[int, int]:
    if len(shape) == 2:
        return shape[0], shape[1]
    if len(shape) == 1:
        return shape[0], 1
    return 1, 1


def _zig_float(x: float) -> str:
    return float(x).hex()


def _zig_floats(vals: list[float]) -> str:
    return ", ".join(_zig_float(x) for x in vals)
