"""Lower a :class:`~shinro.codegen.compose.ComposedGraph` to a Zig data table.

This is Option B of the lowering design: Python emits **data only** — the node
table, the packed constants, and the port layout — never Zig statements. The
actual program (the comptime graph VM) is handwritten once in
``runtime/lower.zig`` and specialized at compile time over this table.

The generated file ``runtime/graph_data.zig`` contains:

- ``nodes``: the flat list of :class:`Node` records — op enum + input ids +
  rows/cols + an ``aux`` index whose meaning depends on the op.
- ``offsets``: per-node buffer offset (node ``i`` owns ``rows*cols`` f64s at
  ``buf[offsets[i]..offsets[i]+rows*cols]``).
- ``buf_len``: total f64 buffer size for one step.
- ``const_blob``: all baked constants, one flat row-major f64 array.
- ``clip_lo``/``clip_hi``: clip bounds, one flat array each.
- ``n_outputs``, ``output_offsets``, ``state_offsets``: port packing into the
  C-ABI ``shinro_step(inputs, outputs, state_out)`` buffers.

Constants are emitted as Zig hex floats (``float.hex()``), which bit-exactly
round-trip the f64 the tracer baked in — the "fixed at compile time" property
holds across the language boundary.

Usage:

    from shinro.codegen.lower_zig import lower_zig
    lower_zig(composed, out_path="runtime/graph_data.zig")
"""

from __future__ import annotations

import json
import os

from shinro.codegen.compose import ComposedGraph
from shinro.codegen.tracing import Graph, Node


def lower_zig(cg: ComposedGraph, out_path: str = "runtime/graph_data.zig") -> None:
    """Serialize a composed graph into a Zig data table at ``out_path``.

    Also writes a deterministic JSON manifest next to it (``<stem>_manifest.json``)
    describing the compiled content — op histogram, port layout, buffer sizes,
    and the ``.solve_qp`` n_vars the graph expects. Same inputs ⇒ byte-identical
    manifest (no timestamps), so manifests are diffable audit records.
    """
    g = cg.graph

    # --- buffer layout: each node owns a slot sized by its shape ---
    offsets: list[int] = []
    total = 0
    for n in g.nodes:
        offsets.append(total)
        total += _size(n.shape)
    buf_len = total

    # --- input port packing (cg.inputs order) ---
    input_offsets: dict[str, int] = {}
    acc = 0
    for name in cg.inputs:
        input_offsets[name] = acc
        acc += _input_size(g, name)

    # --- constants and clip bounds ---
    const_blob: list[float] = []
    const_offsets: dict[int, int] = {}
    clip_lo: list[float] = []
    clip_hi: list[float] = []
    clip_offsets: dict[int, int] = {}

    for i, node in enumerate(g.nodes):
        if node.op == "const":
            const_offsets[i] = len(const_blob)
            const_blob.extend(float(v) for v in node.attrs["value"].ravel())
        elif node.op == "clip":
            clip_offsets[i] = len(clip_lo)
            clip_lo.extend(float(v) for v in node.attrs["lo"].ravel())
            clip_hi.extend(float(v) for v in node.attrs["hi"].ravel())

    # --- output port packing: separate zero-indexed offsets per buffer ---
    # `outputs` and `state_out` are separate C-ABI buffers, so each needs its
    # own cumulative offset table starting at 0.
    output_offsets: list[int] = []
    acc = 0
    for name in cg.outputs:
        output_offsets.append(acc)
        acc += _output_size(g, name)
    state_offsets: list[int] = []
    acc = 0
    for name in cg.state_outputs:
        state_offsets.append(acc)
        acc += _output_size(g, name)

    lines: list[str] = []
    lines.append("// Generated by shinro.codegen.lower_zig — DO NOT EDIT.")
    lines.append("// A ComposedGraph serialized as a comptime data table.")
    lines.append("")
    lines.append("pub const Op = enum {")
    lines.append("    cst, inp, out, matmul, add, sub, mul, div, ne, neg,")
    lines.append("    transpose, inv, reshape, clip, where_op, any,")
    lines.append("    copy, tanh, relu, exp, argmax, one_hot, slice,")
    lines.append("    sin, cos, stack, solve_qp,")
    lines.append("};")
    lines.append("")
    lines.append("pub const Node = struct {")
    lines.append("    op: Op,")
    lines.append("    inputs: []const usize,")
    lines.append("    rows: usize,")
    lines.append("    cols: usize,")
    lines.append("    aux: usize,")
    lines.append("};")
    lines.append("")
    lines.append(f"pub const buf_len = {buf_len};")
    lines.append(f"pub const n_outputs = {len(cg.outputs)};")
    lines.append("")
    lines.append("pub const offsets = [_]usize{")
    lines.append("    " + ", ".join(str(o) for o in offsets) + ",")
    lines.append("};")
    lines.append("")
    lines.append("pub const nodes = [_]Node{")
    for i, node in enumerate(g.nodes):
        lines.append("    " + _node_line(g, i, node, const_offsets, clip_offsets, input_offsets, cg.outputs, cg.state_outputs) + ",")
    lines.append("};")
    lines.append("")
    lines.append("pub const const_blob = [_]f64{")
    if const_blob:
        lines.append("    " + _zig_floats(const_blob) + ",")
    lines.append("};")
    lines.append("")
    lines.append("pub const clip_lo = [_]f64{" + _zig_floats(clip_lo) + "};")
    lines.append("pub const clip_hi = [_]f64{" + _zig_floats(clip_hi) + "};")
    lines.append("")
    lines.append("pub const output_offsets = [_]usize{" + ", ".join(str(o) for o in output_offsets) + "};")
    lines.append("pub const state_offsets = [_]usize{" + ", ".join(str(o) for o in state_offsets) + "};")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    manifest = _graph_manifest(
        cg,
        buf_len,
        len(const_blob),
        offsets,
        const_offsets,
        clip_offsets,
        input_offsets,
    )
    manifest_path = os.path.splitext(out_path)[0] + "_manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")


def _graph_manifest(
    cg: ComposedGraph,
    buf_len: int,
    const_blob_len: int,
    offsets: list[int],
    const_offsets: dict[int, int],
    clip_offsets: dict[int, int],
    input_offsets: dict[str, int],
) -> dict:
    """Build the deterministic graph manifest for a composed graph.

    Describes what the compiled ``.so`` contains (the node table the VM
    executes): op histogram, the ordered node list (dual Python/Zig op names,
    wiring, shape, buffer offset, aux), the C-ABI port layout, buffer sizes,
    and the ``.solve_qp`` n_vars the graph expects. No timestamps — the
    manifest is a pure function of the graph, so identical inputs produce
    identical bytes.

    Args:
        cg: The composed graph being serialized.
        buf_len: Total f64 buffer size for one step.
        const_blob_len: Number of f64s in the baked constants blob.
        offsets: Per-node buffer offset (node ``i`` owns ``rows*cols`` f64s at
            ``buf[offsets[i]..]``).
        const_offsets: Maps const node index → offset into ``const_blob``.
        clip_offsets: Maps clip node index → offset into ``clip_lo``/``hi``.
        input_offsets: Maps input port name → offset into the packed input
            buffer.

    Returns:
        A JSON-serializable dict (keys sorted for stable output).
    """
    g = cg.graph
    op_histogram: dict[str, int] = {}
    for node in g.nodes:
        op_histogram[node.op] = op_histogram.get(node.op, 0) + 1

    def _port(name: str) -> dict:
        for node in g.nodes:
            if node.op == "output" and node.attrs["name"] == name:
                return {"name": name, "shape": list(node.shape)}
        raise KeyError(f"output port '{name}' not found in graph")

    solve_qp = None
    for node in g.nodes:
        if node.op == "solve_qp":
            solve_qp = {"expected_n_vars": _size(node.shape)}
            break

    nodes = []
    for i, node in enumerate(g.nodes):
        vm_op, aux = _node_vm_info(
            g, i, node, const_offsets, clip_offsets, input_offsets, cg.outputs, cg.state_outputs
        )
        rows, cols = _rows_cols(node.shape)
        nodes.append(
            {
                "i": i,
                "op": node.op,
                "vm_op": vm_op,
                "inputs": list(node.inputs),
                "rows": rows,
                "cols": cols,
                "offset": offsets[i],
                "aux": aux,
            }
        )

    return {
        "float_type": "f64",
        "buf_len": buf_len,
        "const_blob_len": const_blob_len,
        "nodes_total": len(g.nodes),
        "nodes": nodes,
        "ops": sorted(op_histogram),
        "op_histogram": op_histogram,
        "inputs": [{"name": n, "shape": list(_input_shape(g, n))} for n in cg.inputs],
        "outputs": [_port(n) for n in cg.outputs],
        "state_outputs": [_port(n) for n in cg.state_outputs],
        "solve_qp": solve_qp,
    }


def _input_shape(g: Graph, name: str) -> tuple[int, ...]:
    """Return the shape of the ``input`` port named ``name``."""
    for node in g.nodes:
        if node.op == "input" and node.attrs["name"] == name:
            return node.shape
    raise KeyError(f"input port '{name}' not found in graph")


# ─── helpers ───────────────────────────────────────────────────────────────


def _node_line(
    g: Graph,
    i: int,
    node: Node,
    const_offsets: dict[int, int],
    clip_offsets: dict[int, int],
    input_offsets: dict[str, int],
    outputs: list[str],
    state_outputs: list[str],
) -> str:
    """Render one Python graph node as a Zig ``Node`` struct literal.

    Translates the Python op/aux mapping into the Zig VM's op enum: ``const``
    → ``cst`` (aux = index into ``const_blob``), ``input`` → ``inp`` (aux =
    offset into the packed input buffer), ``output`` → ``out`` (aux = index
    into ``outputs`` or, for state outputs, ``len(outputs) + index`` so the
    VM can split the two C-ABI buffers), ``where`` → ``where_op``, ``clip``
    → ``clip`` (aux = index into ``clip_lo``/``clip_hi``).

    Args:
        g: The composed graph being serialized.
        i: Node index in ``g.nodes`` (kept for symmetry with the table).
        node: The Python node to render.
        const_offsets: Maps const node index → offset into ``const_blob``.
        clip_offsets: Maps clip node index → offset into ``clip_lo``/``hi``.
        input_offsets: Maps input port name → offset into the packed input
            buffer.
        outputs: Names of the graph's non-state output ports.
        state_outputs: Names of the graph's state output ports.

    Returns:
        A Zig struct literal like ``.{{ .op = .matmul, .inputs = &.{{6, 3}}, ... }}``.
    """
    rows, cols = _rows_cols(node.shape)
    inputs = "&.{" + ", ".join(str(x) for x in node.inputs) + "}"
    op, aux = _node_vm_info(g, i, node, const_offsets, clip_offsets, input_offsets, outputs, state_outputs)

    return f".{{ .op = .{op}, .inputs = {inputs}, .rows = {rows}, .cols = {cols}, .aux = {aux} }}"


def _node_vm_info(
    g: Graph,
    i: int,
    node: Node,
    const_offsets: dict[int, int],
    clip_offsets: dict[int, int],
    input_offsets: dict[str, int],
    outputs: list[str],
    state_outputs: list[str],
) -> tuple[str, int]:
    """Map a Python graph node to its Zig VM ``(op, aux)`` pair.

    This is the single source of truth for the Python→Zig op translation,
    shared by the emitted table (``_node_line``) and the graph manifest:
    ``const`` → ``cst`` (aux = index into ``const_blob``), ``input`` → ``inp``
    (aux = offset into the packed input buffer), ``output`` → ``out`` (aux =
    index into ``outputs`` or, for state outputs, ``len(outputs) + index`` so
    the VM can split the two C-ABI buffers), ``where`` → ``where_op``, ``clip``
    → ``clip`` (aux = index into ``clip_lo``/``clip_hi``), ``slice`` → ``slice``
    (aux = start offset into its input's data). All other ops map to themselves
    with aux = 0.

    Args:
        g: The composed graph being serialized.
        i: Node index in ``g.nodes``.
        node: The Python node to translate.
        const_offsets: Maps const node index → offset into ``const_blob``.
        clip_offsets: Maps clip node index → offset into ``clip_lo``/``hi``.
        input_offsets: Maps input port name → offset into the packed input
            buffer.
        outputs: Names of the graph's non-state output ports.
        state_outputs: Names of the graph's state output ports.

    Returns:
        The ``(vm_op, aux)`` pair for the node.
    """
    if node.op == "const":
        return "cst", const_offsets[i]
    if node.op == "input":
        return "inp", input_offsets[node.attrs["name"]]
    if node.op == "output":
        name = node.attrs["name"]
        if name in outputs:
            return "out", outputs.index(name)
        return "out", len(outputs) + state_outputs.index(name)
    if node.op == "where":
        return "where_op", 0
    if node.op == "clip":
        return "clip", clip_offsets[i]
    if node.op == "slice":
        # slice(x, start, stop): start is the input offset (stop is implicit —
        # the node's rows*cols is stop - start).
        return "slice", node.attrs["start"]
    return node.op, 0


def _input_size(g: Graph, name: str) -> int:
    """Return the flat element count of the ``input`` port named ``name``.

    Args:
        g: The graph being serialized.
        name: The input port name.

    Returns:
        The number of f64s the port occupies in the packed input buffer.

    Raises:
        KeyError: If no ``input`` node with that name exists in the graph.
    """
    for node in g.nodes:
        if node.op == "input" and node.attrs["name"] == name:
            return _size(node.shape)
    raise KeyError(f"input port '{name}' not found in graph")


def _output_size(g: Graph, name: str) -> int:
    """Return the number of f64s an ``output`` port occupies in its C-ABI buffer.

    Args:
        g: The graph being serialized.
        name: The output port name.

    Returns:
        The element count the port takes in the packed ``outputs`` or
        ``state_out`` buffer.

    Raises:
        KeyError: If no output node with that name exists in the graph.
    """
    for node in g.nodes:
        if node.op == "output" and node.attrs["name"] == name:
            return _size(node.shape)
    raise KeyError(f"output port '{name}' not found in graph")


def _size(shape: tuple[int, ...]) -> int:
    """Return the total element count for a shape (empty shape counts as 1)."""
    if not shape:
        return 1
    out = 1
    for d in shape:
        out *= d
    return out


def _rows_cols(shape: tuple[int, ...]) -> tuple[int, int]:
    """Map a graph shape to Zig VM ``rows``/``cols`` (2D → as-is, 1D → (n, 1), else (1, 1))."""
    if len(shape) == 2:
        return shape[0], shape[1]
    if len(shape) == 1:
        return shape[0], 1
    return 1, 1


def _zig_float(x: float) -> str:
    """Format an f64 as a Zig hex float literal (bit-exact round-trip).

    ``float.hex()`` emits the exact binary representation numpy stored, so
    the "fixed at compile time" property holds across the language boundary.
    """
    return float(x).hex()


def _zig_floats(vals: list[float]) -> str:
    """Format a list of f64s as a comma-separated Zig hex-float literal."""
    return ", ".join(_zig_float(x) for x in vals)
