"""Generate ``runtime/tests/mpc_qp.zig`` — the base MPC QP embedded as a Zig test.

Builds the base MPC_LTI controller from ``mpc_lti_base.toml``, extracts the
QP data (H, A, l, u), solves it with OSQP for a sample state, and emits a Zig
test that re-solves the same problem via the cimported OSQP and compares
against the Python oracle.

Run: ``python3 scripts/gen_mpc_qp_test.py``
"""

from __future__ import annotations

import numpy as np
import osqp
from scipy import sparse

from shinro.factories.controller_factory import ControllerFactory
from shinro.utils.array_backend import NumpyBackend


def _fmt(vals, per=8) -> str:
    return ",\n    ".join(
        ", ".join(f"{v:.17g}" for v in vals[i : i + per])
        for i in range(0, len(vals), per)
    )


def _fmt_int(vals, per=16) -> str:
    return ",\n    ".join(
        ", ".join(str(v) for v in vals[i : i + per])
        for i in range(0, len(vals), per)
    )


def main() -> None:
    ctrl = ControllerFactory("src/shinro/configs/controllers/mpc_lti_base.toml").create(
        backend=NumpyBackend()
    )
    H = np.asarray(ctrl.H, dtype=np.float64)
    A = ctrl.A_constraints.tocsc()
    l = np.asarray(ctrl.lcons, dtype=np.float64)
    u = np.asarray(ctrl.ucons, dtype=np.float64)
    n_vars, n_cons = H.shape[0], A.shape[0]

    # OSQP wants P = upper-triangular part of H (symmetric), in CSC.
    P_p, P_i, P_x = [], [], []
    for j in range(n_vars):
        P_p.append(len(P_x))
        for i in range(j + 1):
            v = H[i, j]
            if v != 0.0:
                P_i.append(i)
                P_x.append(v)
    P_p.append(len(P_x))

    A_p = A.indptr.tolist()
    A_i = A.indices.tolist()
    A_x = A.data.tolist()

    x0 = np.array([0.1, -0.2, 0.3])
    q = np.asarray(ctrl.F, dtype=np.float64).T @ x0
    prob = osqp.OSQP()
    prob.setup(sparse.csc_matrix(H), q.flatten(), A, l, u, warm_starting=True, verbose=False)
    u_opt = prob.solve().x

    test = f"""// runtime/tests/mpc_qp.zig — the base MPC QP (mpc_lti_base.toml) solved via
// the cimported OSQP, compared against the Python oracle (mpc_lti.py).
// Generated by scripts/gen_mpc_qp_test.py — DO NOT EDIT.

const std = @import("std");
const c = @cImport({{ @cInclude("osqp.h"); }});

const n_vars = {n_vars};
const n_cons = {n_cons};

// P = upper-tri CSC of H (dense lifted cost)
var P_p = [_]c.OSQPInt{{ {_fmt_int(P_p)} }};
var P_i = [_]c.OSQPInt{{ {_fmt_int(P_i)} }};
var P_x = [_]c.OSQPFloat{{ {_fmt(P_x)} }};

// A = CSC of the block-diag constraint matrix
var A_p = [_]c.OSQPInt{{ {_fmt_int(A_p)} }};
var A_i = [_]c.OSQPInt{{ {_fmt_int(A_i)} }};
var A_x = [_]c.OSQPFloat{{ {_fmt(A_x)} }};

var l = [_]c.OSQPFloat{{ {_fmt(l)} }};
var u = [_]c.OSQPFloat{{ {_fmt(u)} }};
var q = [_]c.OSQPFloat{{ {_fmt(q.flatten())} }};

// expected solution from the Python oracle (same OSQP lib)
const u_expected = [_]f64{{ {_fmt(u_opt)} }};

test "mpc qp matches python oracle" {{
    var P = c.OSQPCscMatrix{{ .m = n_vars, .n = n_vars, .p = &P_p, .i = &P_i, .x = &P_x, .nzmax = P_x.len, .nz = P_x.len, .owned = 0 }};
    var A = c.OSQPCscMatrix{{ .m = n_cons, .n = n_vars, .p = &A_p, .i = &A_i, .x = &A_x, .nzmax = A_x.len, .nz = A_x.len, .owned = 0 }};
    var settings: c.OSQPSettings = undefined;
    c.osqp_set_default_settings(&settings);
    settings.verbose = 0;
    var solver: ?*c.OSQPSolver = null;
    const rc = c.osqp_setup(&solver, &P, &q, &A, &l, &u, n_cons, n_vars, &settings);
    try std.testing.expectEqual(@as(c.OSQPInt, 0), rc);
    defer _ = c.osqp_cleanup(solver.?);

    _ = c.osqp_solve(solver.?);
    const status = solver.?.info.*.status_val;
    try std.testing.expectEqual(@as(c.OSQPInt, 1), status); // OSQP_SOLVED

    const x = solver.?.solution.*.x;
    for (0..n_vars) |j| {{
        try std.testing.expectApproxEqAbs(u_expected[j], x[j], 1e-3);
    }}
}}
"""
    with open("runtime/tests/mpc_qp.zig", "w") as f:
        f.write(test)
    print(f"wrote runtime/tests/mpc_qp.zig (n_vars={n_vars}, n_cons={n_cons}, P nnz={len(P_x)}, A nnz={len(A_x)})")


if __name__ == "__main__":
    main()
