"""Generate the OSQP codegen static solver + the Zig oracle test vectors.

Wraps :func:`shinro.codegen.bake.bake_emosqp` — which emits the
statically-allocated solver into ``<out-dir>/`` (no malloc, no libosqp
dependency) and the ``<out-dir>/solver_meta.zig`` the VM comptime-checks
against — and additionally writes ``src/shinro/runtime/tests/emosqp_data.zig``,
the *data* (sample q and the expected solution) consumed by the handwritten
oracle test ``src/shinro/runtime/tests/emosqp.zig``.

Following the lowerer's doctrine ("Python emits data only, never code"): the
Zig test program is handwritten once and never regenerated; only the two float
arrays are emitted here, as bit-exact hex-float literals (``float.hex()``
round-trips the f64 the oracle produced).

The codegen solver bakes in the problem data (P, A, l, u) and the settings.
For MPC only the linear cost q changes per tick, so ``parameters="vectors"``
(embedded_mode=1) is used. Both the codegen and the oracle use eps=1e-6 so
they converge to the same point.

Warning — shared path, last build wins: by default this script overwrites the
ENTIRE ``src/shinro/runtime/codegen/emosqp/`` tree (and
``src/shinro/runtime/tests/emosqp_data.zig``) for ONE MPC problem. The bake's
n_vars is compiled into fixed-size C arrays, so after regenerating for a
different MPC config, every graph containing a ``.solve_qp`` node from the
previous config is shape-mismatched until the script is re-run for the
original config. The shipped default bakes
``src/shinro/configs/controllers/mpc_lti_base.toml`` (n_vars=30).

To bake a *second* problem without clobbering the shipped default, pass
``--out-dir`` (e.g. a tmp dir) and build the graph against it with
``zig build -Dgraph=<path> -Dsolver_dir=<dir>`` — see
``src/shinro/runtime/README.md``. ``shinro build`` does this automatically for
a scenario declaring ``[compile].solver = "emosqp"``.

Run: ``python3 scripts/gen_emosqp_test.py [--config ...] [--out-dir ...]``
"""

from __future__ import annotations

import argparse
import os

import numpy as np
import osqp
from scipy import sparse

from shinro.codegen.bake import EPS, Bake, bake_emosqp
from shinro.codegen.lower_zig import _zig_floats

DEFAULT_CONFIG = "configs/controllers/mpc_lti_base.toml"
DEFAULT_OUT_DIR = "src/shinro/runtime/codegen/emosqp"
DEFAULT_DATA_PATH = "src/shinro/runtime/tests/emosqp_data.zig"


def bake(config: str, out_dir: str, data_out: str) -> int:
    """Bake the solver (via :func:`bake_emosqp`) and write the oracle vectors.

    Args:
        config: MPC controller TOML config path.
        out_dir: Directory for the codegen solver tree (also receives
            ``solver_meta.zig``).
        data_out: Path for the oracle test vectors.

    Returns:
        The baked problem's n_vars.
    """
    b: Bake = bake_emosqp(config, out_dir)

    # Python oracle for a sample state (same settings): the Zig test vectors.
    # The sample state is sized to the controller's input dimension
    # (MPC_LTI: n_x; MPC_DeltaU: n_x + n_u, the augmented state). F is
    # (n_in, n_vars), so q = Fᵀ x₀ is (n_vars,).
    sample_x0 = np.linspace(0.1, -0.2, b.F.shape[0])
    q = np.asarray(b.F, dtype=np.float64).T @ sample_x0
    oracle = osqp.OSQP()
    oracle.setup(sparse.csc_matrix(b.H), q.flatten(), b.A, b.lb, b.ub, warm_starting=True, verbose=False)
    oracle.update_settings(eps_abs=EPS, eps_rel=EPS)
    u_opt = oracle.solve().x

    data = f"""// src/shinro/runtime/tests/emosqp_data.zig — Generated by scripts/gen_emosqp_test.py — DO NOT EDIT.
// Test vectors consumed by the handwritten oracle test src/shinro/runtime/tests/emosqp.zig.
//
// q = Fᵀ x₀ for the sample state x₀ = {sample_x0.tolist()};
// u_expected is the Python oracle's solution (same OSQP algorithm, eps={EPS:g}).
// Floats are hex literals — bit-exact round-trip of the f64 the oracle produced.

pub const q = [_]f64{{
    {_zig_floats(q.flatten().tolist())},
}};

pub const u_expected = [_]f64{{
    {_zig_floats(u_opt.tolist())},
}};
"""
    with open(data_out, "w") as f:
        f.write(data)

    print(f"wrote {data_out} (n_vars={b.n_vars}, n_cons={b.n_cons})")
    print(f"codegen regenerated in {out_dir}/")
    print(f"wrote {os.path.join(out_dir, 'solver_meta.zig')}")
    return b.n_vars


def main() -> None:
    parser = argparse.ArgumentParser(description="Bake the OSQP codegen static solver for one MPC problem.")
    parser.add_argument("--config", default=DEFAULT_CONFIG, help="MPC controller TOML config (default: mpc_lti_base.toml)")
    parser.add_argument(
        "--out-dir",
        default=DEFAULT_OUT_DIR,
        help="Directory to write the codegen solver tree (default: src/shinro/runtime/codegen/emosqp)",
    )
    parser.add_argument(
        "--data-out",
        default=DEFAULT_DATA_PATH,
        help="Path for the oracle test vectors (default: src/shinro/runtime/tests/emosqp_data.zig)",
    )
    args = parser.parse_args()
    bake(args.config, args.out_dir, args.data_out)


if __name__ == "__main__":
    main()
