"""Generate the Zig-native VM test fixtures (graph + compact weights + vectors).

For each fixture this lowers a composed graph with
:func:`shinro.codegen.lower_zig.lower_zig` (which now emits both numeric blobs
— f64 constants and f32 weights — as raw little-endian ``.bin`` files embedded
at compile time, so they never land in the ``.zig``) and then prepends a
fixture-specific header. The oracle vectors come from
:func:`shinro.codegen.interpret` on seeded random inputs, so the committed graph
and its expected outputs are generated together and stay self-consistent.

Following the repo's "Python emits data only" doctrine, the Zig driver
(``runtime/tests/lower_graph.zig``) is handwritten once; only the graph, the
weight blob, and the vectors are emitted here.

This is a **generate-once** step — it is NOT wired into ``make zig-gen`` or CI.
Run it deliberately, review the diff, commit. It needs the sibling
``shinro-bench`` checkout for the real HF policies (go2, drone_gru); the
``toy_lstm`` fixture lives in this repo, and ``kf_lqr`` comes from the recipe.

Usage::

    python3 scripts/gen_lower_fixtures.py                 # all fixtures
    python3 scripts/gen_lower_fixtures.py --only go2
    python3 scripts/gen_lower_fixtures.py --bench-root ../shinro-bench
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
OUT_DIR = REPO / "src" / "shinro" / "runtime" / "tests" / "graphs"

#: Number of seeded oracle samples per fixture, and the seed (fixed for
#: reproducibility — re-running must reproduce identical vectors).
SAMPLES = 8
SEED = 0
#: Non-QP oracle tolerance (same tier the ctypes oracle uses).
TOL = 1e-12

_ORIG_HEADER = (
    "// Generated by shinro.codegen.lower_zig — DO NOT EDIT.\n"
    "// A ComposedGraph serialized as a comptime data table.\n"
)

#: The fixture menu. ``root`` selects where ``model`` is resolved (the repo or
#: the sibling shinro-bench checkout); ``kind = "classical"`` uses a recipe.
FI = {
    "kf_lqr": {
        "kind": "classical",
        "recipe": "build_base_graph",
        "desc": "closed-loop Kalman filter + LQR (matmul/reshape/add/sub/inv/clip + recurrence)",
    },
    "mpc": {
        "kind": "classical",
        "recipe": "build_mpc_composed_graph",
        "tol": 1e-3,
        "desc": "closed-loop Kalman filter + MPC_LTI (.solve_qp via the baked OSQP solver)",
    },
    "toy_lstm": {
        "kind": "onnx",
        "root": "repo",
        "model": "tests/fixtures/models/toy_lstm.onnx",
        "desc": "committed toy LSTM, H=4 (fused LSTM cell + live state)",
    },
    "go2": {
        "kind": "onnx",
        "root": "bench",
        "model": "tasks/policies/models/go2/policy.onnx",
        "obs_cfg": {"input_name": "obs"},
        "desc": "real Unitree Go2 velocity MLP (4xGemm + 3xElu + obs norm)",
    },
    "drone_gru": {
        "kind": "onnx",
        "root": "bench",
        "model": "tasks/policies/models/drone_gru/policy_v26rnn_dr.onnx",
        "obs_cfg": {"input_name": "state"},
        "desc": "real eco-drone GRU, H=128 (fused GRU cell + live state)",
    },
}


def _build_composed(name: str, spec: dict[str, Any], bench_root: Path):
    """Build the ComposedGraph for one fixture spec."""
    if spec["kind"] == "classical":
        from shinro.codegen import recipes

        return getattr(recipes, spec["recipe"])()
    root = REPO if spec["root"] == "repo" else bench_root
    model = root / spec["model"]
    if not model.exists():
        raise FileNotFoundError(f"{name}: model not found: {model}")
    from shinro.codegen.onnx_import import import_onnx_policy

    return import_onnx_policy(
        str(model),
        obs_cfg=spec.get("obs_cfg"),
        action_cfg={"action_space": "continuous", "deterministic": True},
        output_name=spec.get("output_name"),
    )


def _rewrite_header(graph_path: Path, header: str) -> None:
    """Swap lower_zig's generic header for the fixture-specific one."""
    text = graph_path.read_text()
    graph_path.write_text(text.replace(_ORIG_HEADER, header))


def _rename_sidecars(name: str, graph_path: Path) -> None:
    """Rename lower_zig's ``<stem>_*.bin`` sidecars to the fixture's ``<name>_*.bin``.

    lower_zig names each sidecar after the graph file stem (``<name>_graph``); the
    committed fixtures use ``<name>_weights.bin`` / ``<name>_consts.bin``. A blob
    with no values writes no sidecar, so that case is a no-op.
    """
    for suffix in ("weights", "consts"):
        generated = graph_path.with_name(f"{graph_path.stem}_{suffix}.bin")
        if not generated.exists():
            continue
        target = graph_path.with_name(f"{name}_{suffix}.bin")
        generated.replace(target)
        text = graph_path.read_text().replace(
            f'@embedFile("{generated.name}")', f'@embedFile("{target.name}")'
        )
        graph_path.write_text(text)


def _emit_vectors(name: str, cg, data_path: Path, tol: float) -> tuple[int, int, int]:
    """Run the Python interpreter on seeded inputs; emit the expected vectors."""
    import numpy as np

    from shinro.codegen import interpret
    from shinro.codegen.lower_zig import _zig_floats
    from shinro.codegen.oracle import output_split, pack_arrays, random_inputs

    n_out, n_state = output_split(cg)
    rng = np.random.default_rng(SEED)
    ins, outs, states = [], [], []
    for _ in range(SAMPLES):
        ports = random_inputs(cg, rng)
        ins.append(pack_arrays(cg, ports))
        traced = interpret(cg.graph, ports)
        outs.append(np.concatenate([np.ravel(traced[o]) for o in cg.outputs]))
        if cg.state_outputs:
            states.append(np.concatenate([np.ravel(traced[s]) for s in cg.state_outputs]))
        else:
            states.append(np.zeros(0, dtype=np.float64))
    n_in = int(ins[0].size)
    in_flat = np.concatenate(ins)
    out_flat = np.concatenate(outs)
    state_flat = np.concatenate(states) if n_state else np.zeros(0, dtype=np.float64)

    data_path.write_text(
        f"// Test vectors for `{name}` — generated by scripts/gen_lower_fixtures.py.\n"
        f"// Produced by shinro.codegen.interpret on {SAMPLES} seeded inputs (seed={SEED}).\n"
        f"pub const n_samples = {SAMPLES};\n"
        f"pub const n_in = {n_in};\n"
        f"pub const n_out = {n_out};\n"
        f"pub const n_state = {n_state};\n"
        f"pub const tol = {tol!r};\n"
        f"pub const inputs = [_]f64{{{_zig_floats(in_flat.tolist())}}};\n"
        f"pub const outputs = [_]f64{{{_zig_floats(out_flat.tolist())}}};\n"
        f"pub const states = [_]f64{{{_zig_floats(state_flat.tolist())}}};\n"
    )
    return n_in, n_out, n_state


def generate(name: str, spec: dict[str, Any], bench_root: Path, out_dir: Path) -> None:
    """Generate the graph, weights, and vectors for one fixture."""
    from shinro.codegen.lower_zig import lower_zig

    cg = _build_composed(name, spec, bench_root)
    if spec["kind"] == "classical":
        source = f"recipes.{spec['recipe']}()"
    else:
        root = REPO if spec["root"] == "repo" else bench_root
        source = str(root / spec["model"])
    header = (
        f"// Test fixture `{name}` — {spec['desc']}.\n"
        f"// Generated by scripts/gen_lower_fixtures.py from {source} — DO NOT EDIT.\n"
    )
    graph_path = out_dir / f"{name}_graph.zig"
    data_path = out_dir / f"{name}_data.zig"
    lower_zig(cg, str(graph_path))
    graph_path.with_name(graph_path.stem + "_manifest.json").unlink(missing_ok=True)
    _rename_sidecars(name, graph_path)
    _rewrite_header(graph_path, header)
    n_in, n_out, n_state = _emit_vectors(name, cg, data_path, spec.get("tol", TOL))

    graph_kb = graph_path.stat().st_size / 1024
    weights = graph_path.parent / f"{name}_weights.bin"
    w_kb = weights.stat().st_size / 1024 if weights.exists() else 0.0
    data_kb = data_path.stat().st_size / 1024
    print(
        f"{name:10s} nodes={len(cg.graph.nodes):4d}  n_in={n_in:4d} n_out={n_out:3d} "
        f"n_state={n_state:4d}  graph={graph_kb:8.1f}KB weights={w_kb:8.1f}KB data={data_kb:6.1f}KB"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bench-root", default=str(REPO.parent / "shinro-bench"),
                        help="sibling shinro-bench checkout (default: ../shinro-bench)")
    parser.add_argument("--only", action="append", choices=sorted(FI),
                        help="generate only this fixture (repeatable)")
    parser.add_argument("--out-dir", default=str(OUT_DIR),
                        help="output directory (default: runtime/tests/graphs)")
    args = parser.parse_args()

    out_dir = Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    bench_root = Path(args.bench_root).resolve()

    names = args.only or list(FI)
    for name in names:
        try:
            generate(name, FI[name], bench_root, out_dir)
        except FileNotFoundError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
    # Normalize formatting so regenerating is a no-op against the committed
    # files (lower_zig's output is not necessarily zig-fmt clean).
    if shutil.which("zig"):
        subprocess.run(["zig", "fmt", str(out_dir)], check=False)
    print(f"\nwrote fixtures to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
