"""Generate the OSQP codegen static solver + its Zig oracle test.

Builds the base MPC_LTI from ``mpc_lti_base.toml``, runs OSQP's codegen to
emit a statically-allocated solver into ``runtime/codegen/emosqp/`` (no malloc,
no libosqp dependency), and writes ``runtime/tests/emosqp.zig`` which drives
that solver from Zig and compares against the Python oracle.

The codegen solver bakes in the problem data (P, A, l, u) and the settings.
For MPC only the linear cost q changes per tick, so ``parameters="vectors"``
(embedded_mode=1) is used. Both the codegen and the oracle use eps=1e-6 so
they converge to the same point.

Run: ``python3 scripts/gen_emosqp_test.py``
"""

from __future__ import annotations

import numpy as np
import osqp
from scipy import sparse

from shinro.factories.controller_factory import ControllerFactory
from shinro.utils.array_backend import NumpyBackend

CODEGEN_DIR = "runtime/codegen/emosqp"
TEST_PATH = "runtime/tests/emosqp.zig"
SAMPLE_X0 = np.array([0.1, -0.2, 0.3])
EPS = 1e-6


def _fmt(vals, per=8) -> str:
    return ",\n    ".join(
        ", ".join(f"{v:.17g}" for v in vals[i : i + per])
        for i in range(0, len(vals), per)
    )


def main() -> None:
    ctrl = ControllerFactory("src/shinro/configs/controllers/mpc_lti_base.toml").create(
        backend=NumpyBackend()
    )
    H = np.asarray(ctrl.H, dtype=np.float64)
    A = ctrl.A_constraints.tocsc()
    l = np.asarray(ctrl.lcons, dtype=np.float64)
    u = np.asarray(ctrl.ucons, dtype=np.float64)

    # 1. Generate the static solver (baked with q=0; q is updated per tick).
    prob = osqp.OSQP()
    prob.setup(sparse.csc_matrix(H), np.zeros(H.shape[0]), A, l, u, warm_starting=True, verbose=False)
    prob.update_settings(eps_abs=EPS, eps_rel=EPS)
    prob.codegen(CODEGEN_DIR, parameters="vectors", force_rewrite=True, printing_enable=False)

    # 2. Python oracle for the sample state (same settings).
    q = np.asarray(ctrl.F, dtype=np.float64).T @ SAMPLE_X0
    oracle = osqp.OSQP()
    oracle.setup(sparse.csc_matrix(H), q.flatten(), A, l, u, warm_starting=True, verbose=False)
    oracle.update_settings(eps_abs=EPS, eps_rel=EPS)
    u_opt = oracle.solve().x

    test = f"""// runtime/tests/emosqp.zig — the OSQP codegen static solver driven from Zig.
//
// The generated code (runtime/codegen/emosqp/) bakes the base MPC problem into
// a statically-allocated OSQPSolver global — no malloc, no libosqp dependency.
// This test updates the linear cost q (the only per-tick input for MPC) and
// compares the solution against the Python oracle.
//
// Generated by scripts/gen_emosqp_test.py — DO NOT EDIT.

const std = @import("std");
const c = @cImport({{ @cInclude("osqp.h"); }});

// The statically-allocated solver from workspace.c.
extern var solver: c.OSQPSolver;

const n_vars = {H.shape[0]};

// q = Fᵀ x₀ for the sample state x₀ = {SAMPLE_X0.tolist()}.
const q = [_]c.OSQPFloat{{
    {_fmt(q.flatten())},
}};

// Expected solution from the Python oracle (same OSQP algorithm, eps={EPS:g}).
const u_expected = [_]f64{{
    {_fmt(u_opt)},
}};

test "codegen static solver matches python oracle" {{
    // Update the linear cost (the only per-tick input for MPC), then solve.
    const rc = c.osqp_update_data_vec(&solver, &q, null, null);
    try std.testing.expectEqual(@as(c.OSQPInt, 0), rc);

    _ = c.osqp_solve(&solver);
    const status = solver.info.*.status_val;
    try std.testing.expectEqual(@as(c.OSQPInt, 1), status); // OSQP_SOLVED

    const x = solver.solution.*.x;
    for (0..n_vars) |j| {{
        try std.testing.expectApproxEqAbs(u_expected[j], x[j], 1e-3);
    }}
}}
"""
    with open(TEST_PATH, "w") as f:
        f.write(test)
    print(f"wrote {TEST_PATH} (n_vars={H.shape[0]}, n_cons={A.shape[0]})")
    print(f"codegen regenerated in {CODEGEN_DIR}/")


if __name__ == "__main__":
    main()
