"""Generate the OSQP codegen static solver + the test vectors for its Zig oracle test.

Builds the base MPC_LTI from ``mpc_lti_base.toml``, runs OSQP's codegen to
emit a statically-allocated solver into ``runtime/codegen/emosqp/`` (no malloc,
no libosqp dependency), and writes ``runtime/tests/emosqp_data.zig`` — the
*data* (sample q and the expected solution) consumed by the handwritten oracle
test ``runtime/tests/emosqp.zig``.

Following the lowerer's doctrine ("Python emits data only, never code"): the
Zig test program is handwritten once and never regenerated; only the two float
arrays are emitted here, as bit-exact hex-float literals (``float.hex()``
round-trips the f64 the oracle produced).

The codegen solver bakes in the problem data (P, A, l, u) and the settings.
For MPC only the linear cost q changes per tick, so ``parameters="vectors"``
(embedded_mode=1) is used. Both the codegen and the oracle use eps=1e-6 so
they converge to the same point.

Run: ``python3 scripts/gen_emosqp_test.py``
"""

from __future__ import annotations

import numpy as np
import osqp
from scipy import sparse

from shinro.codegen.lower_zig import _zig_floats
from shinro.factories.controller_factory import ControllerFactory
from shinro.utils.array_backend import NumpyBackend

CODEGEN_DIR = "runtime/codegen/emosqp"
DATA_PATH = "runtime/tests/emosqp_data.zig"
SAMPLE_X0 = np.array([0.1, -0.2, 0.3])
EPS = 1e-6


def main() -> None:
    ctrl = ControllerFactory("src/shinro/configs/controllers/mpc_lti_base.toml").create(
        backend=NumpyBackend()
    )
    H = np.asarray(ctrl.H, dtype=np.float64)
    A = ctrl.A_constraints.tocsc()
    lb = np.asarray(ctrl.lcons, dtype=np.float64)
    ub = np.asarray(ctrl.ucons, dtype=np.float64)

    # 1. Generate the static solver (baked with q=0; q is updated per tick).
    prob = osqp.OSQP()
    prob.setup(sparse.csc_matrix(H), np.zeros(H.shape[0]), A, lb, ub, warm_starting=True, verbose=False)
    prob.update_settings(eps_abs=EPS, eps_rel=EPS)
    prob.codegen(CODEGEN_DIR, parameters="vectors", force_rewrite=True, printing_enable=False)

    # 2. Python oracle for the sample state (same settings).
    q = np.asarray(ctrl.F, dtype=np.float64).T @ SAMPLE_X0
    oracle = osqp.OSQP()
    oracle.setup(sparse.csc_matrix(H), q.flatten(), A, lb, ub, warm_starting=True, verbose=False)
    oracle.update_settings(eps_abs=EPS, eps_rel=EPS)
    u_opt = oracle.solve().x

    data = f"""// runtime/tests/emosqp_data.zig — Generated by scripts/gen_emosqp_test.py — DO NOT EDIT.
// Test vectors consumed by the handwritten oracle test runtime/tests/emosqp.zig.
//
// q = Fᵀ x₀ for the sample state x₀ = {SAMPLE_X0.tolist()};
// u_expected is the Python oracle's solution (same OSQP algorithm, eps={EPS:g}).
// Floats are hex literals — bit-exact round-trip of the f64 the oracle produced.

pub const q = [_]f64{{
    {_zig_floats(q.flatten().tolist())},
}};

pub const u_expected = [_]f64{{
    {_zig_floats(u_opt.tolist())},
}};
"""
    with open(DATA_PATH, "w") as f:
        f.write(data)
    print(f"wrote {DATA_PATH} (n_vars={H.shape[0]}, n_cons={A.shape[0]})")
    print(f"codegen regenerated in {CODEGEN_DIR}/")


if __name__ == "__main__":
    main()
