"""shinro — Whole-body control framework for the lekiwi robot.

A modular robotics control stack with four abstract base classes and
concrete implementations for trajectory generation, control, state
estimation, and plant dynamics.

Subpackages:
    shinro.trajectories — Reference path generators (CubicPolynomial, QuinticPolynomial)
    shinro.controllers  — Control algorithms (LQR, PID, MPC)
    shinro.plants       — Robot models (ArmRobot, HolonomicMobileRobot)
    shinro.estimators   — State estimation (KalmanFilter, LuenbergerObserver)
    shinro.factories    — Registry-based component factories (TOML config driven)
    shinro.simulation   — Generic robot simulation factory
    shinro.mcp          — Model Context Protocol server exposing the control suite
"""

from shinro.components import Controller, PhysicsEngine, Plant, StateEstimator, TrajectoryGenerator

try:
    from shinro._version import __version__  # generated by setuptools-scm
except ImportError:  # pragma: no cover
    __version__ = "0.0.0"

__all__ = [
    "Controller",
    "Plant",
    "StateEstimator",
    "TrajectoryGenerator",
    "PhysicsEngine",
    "__version__",
]
