"""shinro — Whole-body control framework for modular robotics.

A modular robotics control stack built on five abstract base classes —
Controller, Plant, StateEstimator, TrajectoryGenerator, and PhysicsEngine —
with concrete implementations for trajectory generation, control, state
estimation, and plant dynamics. Components are assembled from TOML config
via registry-based factories and can run on numpy or torch backends.

Subpackages:
    shinro.trajectories  — Reference path generators (CubicPolynomial, QuinticPolynomial)
    shinro.controllers   — Control algorithms (LQR, PID, MPC, MPPI, SMC)
    shinro.plants        — Robot models (ArmRobot, HolonomicMobileRobot)
    shinro.estimators    — State estimation (KalmanFilter, LuenbergerObserver)
    shinro.physics_engine — Physics engine adapters (MuJoCo)
    shinro.factories     — Registry-based component factories (TOML config driven)
    shinro.simulation    — Generic robot simulation factory
    shinro.mcp           — Model Context Protocol server exposing the control suite
    shinro.codegen       — Trace → compose → interpret → lower pipeline
    shinro.utils         — Array backend, linearization, controllability analysis
"""

from shinro.components import Controller, PhysicsEngine, Plant, StateEstimator, TrajectoryGenerator

try:
    from shinro._version import __version__  # generated by setuptools-scm
except ImportError:  # pragma: no cover
    __version__ = "0.0.0"

__all__ = [
    "Controller",
    "Plant",
    "StateEstimator",
    "TrajectoryGenerator",
    "PhysicsEngine",
    "__version__",
]
