// runtime/codegen/emosqp/solver_meta.zig — Generated by scripts/gen_emosqp_test.py — DO NOT EDIT.
// The baked solver's variable count. runtime/lower.zig comptime-checks that
// any graph containing a .solve_qp node matches this n_vars at build time.
// The remaining consts are provenance surfaced in the build manifest.

pub const n_vars: usize = 30;
pub const n_cons: usize = 60;
pub const eps: f64 = 1e-06;
pub const config = "configs/controllers/mpc_lti_base.toml";
pub const config_sha256 = "bca82482e84be128188bf0ddc63c15a260da68e457cb494bc4d2181d99d643a6";
pub const python_version = "3.12.3";
pub const numpy_version = "2.4.6";
pub const scipy_version = "1.18.0";
pub const osqp_version = "1.1.3";
